export const DATA_SETS = [
  [
    // 그린비
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_kangsojung.jpg',
      title: 'New-Etiquette Project',
      author: '강소정',
      instagram: ['szunok'],
      text: '이른바 뉴-에티켓 프로젝트는 범람 시대 속 클릭 한 번, 좋아요 한 번으로 소비되고 버려지는 인스턴트 관계성들을 극복하기 위해 탄생되었다. 이것은 우리가 이미 실행하고 있는 암묵적인 배려들을 ‘에티켓’의 범주 안에서 새롭게 재분류한 것으로, 지극히 일상적이면서도 타인과의 직접적인 접촉을 요한다. 뉴-에티켓을 통해 관계를 깊게, 또 느리게 음미해보자.',
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kangsojung_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kangsojung_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kangsojung_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kangsojung_4.jpg',
      ],

      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_kimgyubeen.jpg',
      title: 'All-in-One Impromptu',
      author: '김규빈',
      text: 'Epson L4150과 함께 연주한다. 좀처럼 마음대로 움직여 주지 않는 나의 복합기는 같은 데이터를 매번 다르게 산출해 낸다. 결과는 예상할 수 없다. 지면 여백을 무시하기도 하고, 검은색 글씨를 하얀색으로 출력하기도 한다. 디지털로 이루어진 동일한 데이터들은 나의 복합기를 거치며 각기 다른 형태로 변화한다.',
      instagram: ['streetpessimist'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_1.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_2.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_3.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_4.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_5.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_6.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_7.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_8.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_9.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimgyubeen_10.jpeg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_yanghaedeun.jpg',
      title: '지면에 지면을 지면',
      author: '김린, 양해든',
      text: '지당히 디딘 채 지나쳐간 수많은 지면(地面)은 한 장의 지면(紙面) 위에 지어졌고, 우리가 관심할 때 비로소 저마다의 정체성을 향유한다. ‘지면에 지면을 지면’은 땅의 거죽을 종이의 겉면으로 옮기는 과정과 그에 따른 가시적 결과물을 포괄한다.',
      instagram: ['_haedeun', 'lyynkm'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yanghaedeun_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yanghaedeun_2.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_kimminju.jpg',
      title: 'UWW(Universe Wide Web)',
      author: '김민주',
      text: 'UWW(Universe Wide Web)는 기존의 지구 내에서만 사용되던 WWW을 바탕으로 제작된 인터넷서비스입니다. UWW를 통해 외계행성을 탐험하고 시공간을 초월하여 메시지를 전송해 보세요. 무한한 우주를 향해 한 걸음 다가서세요.',
      instagram: ['juya_0905'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_8.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_9.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimminju_10.jpg',
      ],
      video: [],
      link: [
        'https://www.figma.com/proto/7nJ4AC0tKelAjujmcWmxgy/UWW?page-id=0%3A1&type=design&node-id=13-116&viewport=12%2C7%2C0.07&t=0OAcpDkHsm1kxWoE-1&scaling=contain&starting-point-node-id=13%3A116',
      ],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_sooakhym.jpg',
      title: 'Desperate Dance to Doom',
      author: '김수아',
      text: '1999년 12월 31일, 모든 컴퓨터가 멈추고 세계 종말의 카운트다운이 시작된다. 테크노 클럽 Y2K는 멸망을 춤으로 잊어버리려는 필사적 댄스 파티를 벌인다. 죽음의 순간이 두려우십니까? 피할 수 없다면 즐겨라! ',
      instagram: ['soo.a.khy.m'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_sooakhym_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_sooakhym_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_sooakhym_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_sooakhym_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_sooakhym_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_sooakhym_6.jpg',
      ],
      video: ['https://www.youtube.com/embed/uId97Qz3Jfs?si=pnf8BM2B-3rlvf1B'],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_kimeugene.jpg',
      title: 'New Value',
      author: '김유진',
      text: '마르셀 뒤샹이 레디메이드를 고안하게 된 이유는 무엇이었을까요? 아마 그는 지금의 우리와 같은 기분이었을 겁니다. 매일 새로운 브랜드가 쏟아지고, 우리 모두는 새로운 제품 아이디어를 내는 것에 지쳤어요. 그냥 기성품에 로고만 새겨서 판매할 겁니다. 세계 최초 레디메이드 브랜드인 우리는, 말 그대로 ‘새롭고, 특별하고, 유일무이한 가치’라고 새겨서 사물의 새로운 가치를 만들어낼 거예요. 그리고 그것이 우리 브랜드의 차별점이 될 겁니다.',
      instagram: ['eiiig_giiie'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimeugene_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimeugene_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimeugene_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_kimeugene_4.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_parksumin.png',
      title: '사유의 서재',
      author: '박수민',
      text: '생각하기에 살아가는 인간에게, 그리고 사유하는 모든 존재들을 위해. 사유의 서재 [biblĭŏthéca de cogĭtátĭo] 의 모든 것들은 방문객에게 질문합니다. ‘당신은 어떤 생각을 하고 있나요?’',
      instagram: ['me.llamo_llamo'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-01.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-02.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-03.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-04.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-05.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-06.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-07.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-08.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-09.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_parksumin-10.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_bakyejin.jpg',
      title: 'Blob sockS',
      author: '박예진',
      text: '발의 모양은 제각각이지만 양말은 각자의 발에 맞게 변합니다. ‘Blob sockS’는 이런 양말의 특징을 점균류라는 단세포 생명체와 연결시킨 양말 브랜드입니다. \r\n점균류는 괴생명체같이 보이지만 발이 없어도 이곳저곳 옮겨 다닐 수 있고, 소화기관이 없는데도 여러 다른 생물들을 잡아먹을 수 있습니다. 심지어는 뇌나 신경계가 없는데도 기억을 하고 학습을 합니다.점균류가 가지고 있는 유일무이한 특징을 담은 양말을 선보입니다!',
      instagram: ['yeworksdesign'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_bakyejin_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_bakyejin_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_bakyejin_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_bakyejin_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_bakyejin_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_bakyejin_6.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_yeongeunEo.jpg',
      title: 'fil(+)aylist',
      author: '어영은',
      text: '범람하는 자기표현의 시대 속에서 우리는 종종 길을 잃기도 합니다.\r\n그런 당신에게 길잡이가 되어줄 〈 fil(+)aylist 〉\r\n당신에게 어울리는 음악(playlist), 그리고 인스타그램 필터(filter)를 추천해 드립니다!',
      instagram: ['_0urloveisgreat'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yeongeunEo_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yeongeunEo_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yeongeunEo_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yeongeunEo_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yeongeunEo_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yeongeunEo_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_yeongeunEo_7.jpg',
      ],
      video: [],
      link: ['https://smore.im/quiz/h02nr2m9DS'],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_ohyoonseoleeyeonu.jpg',
      title: 'SPYSPECT',
      author: '오윤서, 이연우',
      text: '39xx년, 외계에서 온 우주인 woo와 oh가 우연한 사고로 지구에 착륙했습니다. 새로운 환경에 적응하며 존재를 숨기는 동안, 지구인들의 표면에 감춰진 정체성을 이해하기 위한 특수 안경을 제작합니다. 그 특별한 안경은 우리에게 새로운 가능성을 보여주었습니다. 이제 우리, woo와 oh는 지구인 탐색 사업을 시작합니다.',
      instagram: ['y0_13s', '_u_ye0n'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_1.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ohyoonseoleeyeonu_8.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_ryueunji.jpg',
      title: 'Musée des Trucs Qui m’ont Choqué',
      author: '유은지',
      text: 'Musée des Trucs Qui m’ont Choqué는 ‘나에게 충격을 준 것들에 대한 박물관’이라는 뜻이다. 인류는 일상의 큰 부분을 인터넷과 소셜 미디어에 의존하기 시작한 지 수십 년이 되어가는 동안 다방면에서 취약해졌다. 이제 그들은 왜곡된 입력, 과대 해석된 분류, 모방으로부터 나오는 출력의 과정을 통해 정보를 처리하게 되었다. 각 단계를 보여주는 세 전시실을 관람하며 망가진 정보 처리 프로세스를 몰래 들여다보자.',
      instagram: ['neunji.archive'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_ryueunji_8.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_Yoon chaiwon.jpg',
      title: 'Ruminola village',
      author: '윤채원',
      text: '어서 오세요! 루미놀라 마을에 오신 것을 환영합니다. 저희 마을은 정체성의 위기라는 큰 재앙을 이겨낸 정체불명 생명체들이 모여 만들어진 마을입니다. 위기를 견뎌내고 살아남은 여러분, 루미놀라에 입주할 수 있는 특별한 기회를 놓치지 마세요!',
      instagram: ['ycwony'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_Yoonchaiwon_8.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_leeyeonju.jpg',
      title: 'Look at the real self',
      author: '이연주',
      text: '작업을 시작할 때 가장 먼저 레퍼런스를 찾곤 한다. 세상에는 멋진 이미지가 이미 너무 많으니까. 세상에는 이미지가 너무 많아서 왜 이렇게 만들었을지는 고민할 시간이 없고는 하지만, 오늘만큼은 자세히 들여다보자. 그리고 그 안에 숨겨진 모습을 발견하자.',
      instagram: ['yeo.nnju'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeonju_8.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_leeyeeun.jpg',
      title: 'Infinity',
      author: '이예은',
      text: '수렴적 상향구조를 가진 팽창 우주는 그 특성이 마치 헤겔의 변증법과 유사해 보이기도 합니다. 변증법적 시선으로 우주의 무한함을 따라가다 보면, 우주는 우리를 무한한 발견과 새로운 가능성으로 이끕니다. 끝없는 시공간 속에서 우리는 또 무엇을 찾게 될까요? Infinity와 함께 새로운 여행이 시작됩니다.',
      instagram: [],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeeun_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeeun_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeeun_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeeun_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeeun_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leeyeeun_6.jpg',
      ],
      video: ['https://www.youtube.com/embed/hOuLFsYohdM?si=8xDugjzTX_nXyj0o'],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_leejiwon.jpg',
      title: 'TTfestival',
      author: '이지원',
      text: '자본주의의 시대라는 이름 아래 스스로를 판매대 위에 올리는 사람들, 깎여나가는 자신만큼 생기는 고민과 고뇌, 그리고 그를 폄하하는 세태. 우리는 그런 사람들을 위해 "쓰레기" 같은 고민을 던지는 축제를 개최했습니다. 누구든 편히 고뇌하고 앓을 수 있습니다. 이 축제가 끝나는 날에, 조금 더 서로를 이해하고 화합할 수 있길 바랍니다.',
      instagram: ['LeeJIwon'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_8.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_9.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_leejiwon_10.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_jeonjiwon.jpg',
      title: 'ememi',
      author: '전지원',
      text: 'ememi(egg me my identity)는 독보적인 커스터마이징 젤리를 선사합니다. 개성이 퇴색되며 표준화된 세상에서, 독특한 정체성을 존중함과 동시에 당신만의 개성을 성장시키는 ememi와 함께 특별하고 독창적인 존재로 거듭나세요.',
      instagram: ['wonnieji__'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jeonjiwon_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jeonjiwon_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jeonjiwon_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jeonjiwon_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jeonjiwon_5.jpg',
      ],
      video: ['https://www.youtube.com/embed/iyj9D2249xU?si=DNqjgU9vFXPcyvlF'],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_jungyewon.jpg',
      title: 'Fever Fish',
      author: '정예원',
      text: '열병을 앓고 있는 사람들의 눈앞에서는 자유롭게 유영하는 물고기가 일렁거린다. 혼란스럽고 불확실한 청춘의 시기에 찾아온 물고기들, 내게 보이는 물고기의 종류를 알면 이 지독한 열병을 진단할 수 있지 않을까.',
      instagram: ['ywon_512'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_8.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_jungyewon_9.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_josungwan.jpg',
      title: 'Permaphic 1.0',
      author: '조승완',
      text: '오래된 컴퓨터 한 구석에서 이상한 프로그램을 발견했다. 잃어버린 그래픽을 찾아 주는 Permaphic 그래픽 생성기...? Permaphic 그래픽 생성기를 통해 나의 잃어버린 그래픽을 찾아나가 보자.',
      instagram: ['sungwanizer'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_josungwan_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_josungwan_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_josungwan_3.png',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_josungwan_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_josungwan_5.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_joyerin.jpg',
      title: 'Basic Instinct (원초적 본능)',
      author: '조예린',
      text: '미디어와 자본이 인류의 사고와 행동을 결정하는 현대, 인류는 주체성을 잃어버리고 문명의 노예가 되었다. 한 연구단체는 이에 대항하기 위해 인간의 본원을 회복해 탈의존화된 신인류를 만들어내는 프로젝트 〈원초적 본능〉을 비밀리에 착수한다. 원초적 신인류는 문명에 의해 무뎌진 치아구조를 탈피하고 인간의 본질적인 형태를 갖추어나간다.',
      instagram: ['yelling_bird'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_01.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_02.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_03.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_04.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_05.png',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_06.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_07.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_08.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_09.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_joyerin_10.jpg',
      ],

      video: [
        'https://www.youtube.com/embed/DmTyrAGV0z0?si=m6V3dq4u8XO4rocF',
        'https://www.youtube.com/embed/zYQcK30Cb8w?si=0PsLfJNFQ6Efx8V6',
      ],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_chohoonkyu.jpg',
      title: 'plantform',
      author: '조훈규',
      text: 'Make your own plant! plantform은 당신이 선택한 식물들로만 조합된 세상에 하나뿐인 식물을 선물해 드립니다. planform의 독특한 방식을 통해 당신만의 새로운 리폼식물을 만들어보세요. 지금 바로 주문서를 작성해보세요!',
      instagram: ['hooonkyu'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_1.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_2.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_3.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_4.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_5.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_6.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_7.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_8.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_9.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_chohoonkyu_10.jpeg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_hasumin.jpg',
      title: '옅어져 사라진다',
      author: '하수민',
      text: '겨울엔 동백나무가, 봄엔 벚꽃이 아름답게 피어나 세상을 오색찬란한 빛으로 물들인다. 다채로운 색채로 자연을 가꾸어 주던 꽃잎들은 표준화된 기준에 자신을 맞추려 본래의 색을 서서히 잊어간다. 선명히 옅어져가는 꽃잎들 속에서 우리는 어떤 색의 꽃을 피워내고 싶은가.',
      instagram: ['sx.xxn_'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hasumin_1.JPG',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hasumin_2.JPG',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hasumin_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hasumin_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hasumin_5.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_thumbnail_hyunhyeyeong.jpg',
      title: 'DREAM AUCTION',
      author: '현혜영',
      text: '태어날 때부터 녹화되는 꿈 테이프를 사고파는 세계. 우리는 오늘도 누군가에게 낙찰받은 꿈을 꾸며 살고 있습니다. 다음 테이프의 주인공은 누구일까요? 꿈과 현실의 경계선 앞에서, 지금부터 경매를 시작합니다!',
      instagram: ['aeyongs2'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hyunhyeyeong_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hyunhyeyeong_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hyunhyeyeong_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hyunhyeyeong_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/greenbee_hyunhyeyeong_5.jpg',
      ],
      video: [],
      link: [],
    },
  ],
  [
    // 드로마픽
    {
      thumbnail: 'https://imgur.com/dcJRnuw.jpg',
      title: '수살귀',
      author: '남주현, 김성윤, 박소현, 안가은, 여단아, 이세라, 김건우, 정병준, 정현욱',
      text: '물에 비친 도망자를 발견한 수살귀: 映 반사를 통해 도망자의 몸에 자신을 투영하려한다. 거울 속 도망자의 죽음을 부르는 수살귀와 끊임없이 흔들리는 도망자, 두 존재의 끔찍한 교감을 담아냈다.\r\n\r\n참여자: 남주현, 김성윤, 박소현, 안가은, 여단아, 이세라, 김건우, 정병준, 정현욱',
      instagram: [],
      image: [
        'https://imgur.com/dBMavA9.jpg',
        'https://imgur.com/neCMdUk.jpg',
        'https://imgur.com/sI5qF7c.jpg',
        'https://imgur.com/NkMIFWj.jpg',
        'https://imgur.com/LE18nrL.jpg',
        'https://imgur.com/hhj8rBf.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/mUZmQ3W.jpg',
      title: '흙불땀: 젊은 예술가들에게',
      author: '여단아, 정병준, 정현욱, 이다연',
      text: '방황하는 젊은 예술가들에게 따뜻한 조언과 위로를 전하는 도예가 이인진 작가님에 대한 다큐멘터리.\r\n\r\n참여자: 여단아, 정병준, 정현욱, 이다연',
      instagram: [],
      image: [
        'https://imgur.com/Z0weMGi.jpg',
        'https://imgur.com/XOtKXet.jpg',
        'https://imgur.com/CidT5sQ.jpg',
        'https://imgur.com/SReCmTy.jpg',
        'https://imgur.com/oUphQ9C.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/K1LIGc6.jpg',
      title: 'NOOK',
      author: '이윤정,한준,김지호,이혜지,박기정,이다연',
      text: '스위스 취리히 대학 수의학과와 홍익대학교 패션디자인과 협력 프로젝트로 디자인 된 테크웨어 패션필름 \r\n\r\n참여자: 이윤정,한준,김지호,이혜지,박기정,이다연',
      instagram: ['mmockkingjay'],
      image: ['https://imgur.com/OxspG33.jpg', 'https://imgur.com/GVp7K5G.jpg'],
      video: ['https://player.vimeo.com/video/902037245?h=0260e25fc8'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/wuoqd2e.jpg',
      title: 'SOBER',
      author: '이윤정, 정현욱, 주영은',
      text: '아이클라우드 서비스를 제공하는 가상 브랜드 프로모션 필름 \r\n\r\n참여자: 이윤정, 정현욱, 주영은',
      instagram: ['mmockkingjay'],
      image: ['https://imgur.com/21yp0y4.jpg', 'https://imgur.com/1592Dc6.jpg'],
      video: ['https://player.vimeo.com/video/902036368?h=fc3635f7f2'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/OCxbcIc.jpg',
      title: '한 줌의 생명이 채울 수 있는',
      author: '이은제, 고도형, 김민서, 김채은, 문을주, 오연재, 오성건, 이다연, 이세라, 정병준',
      text: '아주 작은 존재와의 짧은 만남이 남긴 복잡 미묘한 감정을 따스하게 일렁이는 영상 속에 담아보았다.\r\n\r\n참여자:이은제, 고도형, 김민서, 김채은, 문을주, 오연재, 오성건, 이다연, 이세라, 정병준',
      instagram: ['imxmit'],
      image: [
        'https://imgur.com/tgmwqOA.jpg',
        'https://imgur.com/3dm9MoJ.jpg',
        'https://imgur.com/FhAX69p.jpg',
        'https://imgur.com/muL46pL.jpg',
        'https://imgur.com/ilD4D66.jpg',
        'https://imgur.com/pVJVk1S.jpg',
      ],
      video: ['https://www.youtube.com/embed/JUM0iANC-FA?si=rqRFGSk1GpKa63BP'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/3Aw5ajD.jpg',
      title: '삼매경 samadhi 三昧境',
      author: '정민경, 강동준, 이다연, 조서영',
      text: '잡념을 버리고 한 가지 대상에만 정신을 집중하는 경지에 이른 사람이 있다. \r\n부디 바른 지혜를 얻고 올바르게 대상을 파악하기를.\r\n\r\n참여자: 정민경, 강동준, 이다연, 조서영',
      instagram: ['mellomaisie', 'kangdongjoonvideo', 'violetwavemovie', 'choseoyoungcho'],
      image: [
        'https://imgur.com/wsShr2m.jpg',
        'https://imgur.com/MPer9wa.jpg',
        'https://imgur.com/MPer9wa.jpg',
        'https://imgur.com/kdfTXW0.jpg',
        'https://imgur.com/JIrpOiz.jpg',
        'https://imgur.com/bQCFbRa.jpg',
        'https://imgur.com/6WDDAh0.jpg',
        'https://imgur.com/szGriQ4.jpg',
        'https://imgur.com/c8Ahe12.jpg',
        'https://imgur.com/EXJr18S.jpg',
      ],
      video: ['https://www.youtube.com/embed/1CWFl0FNNEM?si=etTRCacF0lkuEqyD'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/SmfUoTq.jpg',
      title: 'IMOOGI',
      author: '정병준,김민서,홍지윤,백유석',
      text: '날아오르자. 무엇을 꿈꾸던. 용이 되어 자유로이 펼쳐보자. 비상하는 용을 꿈꾸는 이무기처럼 우리도 마음껏 꿈을 꾸고 춤을 추기를.\r\n\r\n\r\n참여자: 정병준,김민서,홍지윤,백유석',
      instagram: ['jbjoon3712'],
      image: [
        'https://imgur.com/WU2DgH8.jpg',
        'https://imgur.com/dwPKI4D.jpg',
        'https://imgur.com/1RUULCY.jpg',
        'https://imgur.com/C96ERJr.jpg',
        'https://imgur.com/dagwfey.jpg',
        'https://imgur.com/m53jH22.jpg',
        'https://imgur.com/qzBDYxD.jpg',
        'https://imgur.com/UjDudLK.jpg',
      ],
      video: ['https://www.youtube.com/embed/0bnj-SuNkhQ?si=FZHHesTyaIbnBjbp.jpg'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/UvLbmi4.jpg',
      title: 'Crocodile(meal)',
      author: '홍지윤, 박소현, 안서원, 이다연, 이주영, 정현욱',
      text: '먹는 것이 재미인 악어. 코스요리로도 모자란 악어의 성찬.\r\n영상 곳곳에서 악어의 특징과 식습관을 찾아볼 수 있다.\r\n\r\n\r\n참여자: 홍지윤, 박소현, 안서원, 이다연, 이주영, 정현욱',
      instagram: ['dvonhong'],
      image: ['https://imgur.com/U4bi8PM.jpg', 'https://imgur.com/o0HIbP9.jpg', 'https://imgur.com/UvLbmi4.jpg'],
      video: ['https://www.youtube.com/embed/zgJGUo6gvXA?si=P8NSGDWURF8Mmurm'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/GwCHIai.jpg',
      title: '우리가 오직 (숫자)여야만 할 수 있는 것들!',
      author:
        '홍지윤, 김민서, 김성윤, 김채은, 남주현, 문을주, 박소현, 안가은, 안서원, 오연재, 이다연, 이은제, 이주영, 최세은',
      text: '(숫자)여야만 의미 있는 것들이 있다. 가령, 혼자여야만 의미있는 행동 등! 6명이 해야만 설득력이 있는 것에는 무엇이 있을까? 이때 숫자는 일상적인 것일 수도, 아이코닉한 메타포일 수도 있다. 세상에 의미 없는 숫자는 없다. 숫자는 계속된다. 인생은 계속된다!\r\n\r\n참여자: 홍지윤, 김민서, 김성윤, 김채은, 남주현, 문을주, 박소현, 안가은, 안서원, 오연재, 이다연, 이은제, 이주영, 최세은',
      instagram: ['dvonhong', 'violetmoviewave'],
      image: ['https://imgur.com/JyaXBz8.jpg', 'https://imgur.com/GwCHIai.jpg', 'https://imgur.com/gNpbLv5.jpg'],
      video: ['https://www.youtube.com/embed/E462KLVfYnQ?si=MoiZBkUX07snyoHV'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/uCx9oSb.jpg',
      title: '무제',
      author: '황지원',
      text: '이름 붙여지지 않은 다수한 실험을 응원하며.\r\n\r\n참여자: 황지원',
      instagram: ['now_iz'],
      image: [
        'https://imgur.com/0SGztO8.jpg',
        'https://imgur.com/XWOemCh.jpg',
        'https://imgur.com/YHWWfRD.jpg',
        'https://imgur.com/8ySAixD.jpg',
      ],
      video: [],
      link: [],
    },
  ],
  [
    // 아이레이
    {
      thumbnail: 'https://imgur.com/tE7Xc2e.jpg',
      title: '2024 Showreel',
      author: '강보영, 김민하',
      text: '어두워진 방에서 혼자서 열심히 컴퓨터 작업을 하고 있는 주인공! 작업에 난항을 겪고 있지만 작업을 멈출 수는 없다. 아이레이 부원들이 2023년에 열심히 만든 작업들을 보여주는 쇼릴. 환상적인 3D 작업의 세계로 여러분을 초대합니다!',
      instagram: ['boyoung115', 'ashkm237'],
      image: [
        'https://imgur.com/iPkLSYJ.jpg',
        'https://imgur.com/kGbH8Cz.jpg',
        'https://imgur.com/3AqEX2U.jpg',
        'https://imgur.com/qQAyeXh.jpg',
        'https://imgur.com/o66rlnT.jpg',
      ],
      video: ['https://www.youtube.com/embed/pXAThH5BIkM?si=njewzqs0TDiux99S'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/2IQRA61.jpg',
      title: '2024 Promotion Video',
      author: '구한나, 권용희, 김유은, 김현민, 맹지연',
      text: '어스름한 골목에서 정체모를 누군가에게 쫓기는 가오리 레이, 인간세계의 유일한 포털을 찾아 집으로 돌아가기 위한 레이의 여정이 시작된다! 아이레이의 마스코트-레이를 따라 펼쳐지는 환상적인 3D의 세계로 여러분을 초대합니다!',
      instagram: [],
      image: [
        'https://imgur.com/3hXTAam.jpg',
        'https://imgur.com/ZoxTXRA.jpg',
        'https://imgur.com/XngVGRz.jpg',
        'https://imgur.com/N86AHI6.jpg',
        'https://imgur.com/IpVZi5w.jpg',
      ],
      video: ['https://www.youtube.com/embed/1r-7Wl0HJuY?si=IDzYU_sbXOItMllB'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/qyIKusV.jpg',
      title: 'Polyphony Vortex Motion Poster',
      author: '김민하',
      text: '이번 전시 Polyphony Vortex는 3D 아트의 장점을 살려 기계적 모델링과 투명한 머티리얼에서 나오는 청량함을 주제로 Y2K 스타일의 아이덴티티를 만들었습니다.',
      instagram: ['ashkm237'],
      image: ['https://imgur.com/JvxAM7D.jpg', 'https://imgur.com/FEstAHP.jpg'],
      video: ['https://player.vimeo.com/video/918672968?h=09f906c537'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/gwKXAXQ.jpg',
      title: '달무티: 혁명의 시작',
      author: '권용희, 강민서, 조윤진, 정수연, 최현아',
      text: '계급사회 속 흘러가는 일상을 살아가는 사람들과 끝없이 위로 올라가는 재화들. 그 속에서 삶은 불공평하다는 달무티의 패러다임을 깨트리는 존재의 등장?! 일상을 몰래 지켜보는 누군가를 발견한다면 주의 깊게 관찰해보는 건 어떨까?',
      instagram: [],
      image: ['https://imgur.com/902iyaL.jpg', 'https://imgur.com/bDAJDWW.jpg'],
      video: ['https://www.youtube.com/embed/HR7sAxAGpDs?si=DAZOJADezLAMXOSs'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/LjivI6y.jpg',
      title: 'LET MAMA COOK!',
      author: '김연재, 권선주, 손서영, 손수민, 최유빈',
      text: '호러 테마로 재해석한 Aggressive한 버전의 쿠킹마마 웹게임. 여기서 엄마와 함께 평생 살든지, 아니면 너의 요리 실력을 증명해서 당당히 나가든가 해!',
      instagram: [],
      image: ['https://imgur.com/b1gLkB3.jpg', 'https://imgur.com/Y7qewLc.jpg'],
      video: ['https://www.youtube.com/embed/gG2hbKQZ4vA?si=b4N6UtWLj9q-ahRvs'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/45dTKOS.jpg',
      title: '마녀 주방 대모험',
      author: '김유은, 김지후, 신수진, 안기진, 이선우',
      text: '가지각색의 쿠키들이 평화롭게 살고 있는 쿠키마을. 마을 한가운데에 동상을 세우려고 하는데 이런, 동상의 재료인 밀가루가 부족해! 마녀의 주방에는 밀가루가 있다고 들었는데, 과연 누가 위험천만한 마녀의 주방에서 밀가루를 가져올까? 걱정 마! 나, 용감한 쿠키만 믿으라고! 이렇게 우리의 용감한 쿠키군은 마녀의 주방으로 대모험을 떠나는데, 과연 그는 밀가루를 무사히 쿠키마을로 가져올 수 있을까?',
      instagram: [],
      image: ['https://imgur.com/OqRPzOp.jpg', 'https://imgur.com/Irbxdrm.jpg'],
      video: ['https://www.youtube.com/embed/sxGpWdwRZYE?si=dcsw1OCVl5KBQZaN'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/RLmM5bV.jpg',
      title: 'F40.1',
      author: '구한나, 김현유, 문미루, 이민경, 정예은',
      text: '만원 지하철에서 잠이 든 소녀. 눈을 떠 보니 사람들은 마네킹으로 바뀌어 있고, 지하철은 식물로 뒤덮여 있다. 소녀는 여러 장소에서 탈출해 꿈속에서 깨어나야만 한다. 그러나 여러 장소를 돌아다니던 소녀는 꿈이 자신의 시선공포증과 관련 있다는 사실을 알게 되는데…….',
      instagram: ['k1rk1v'],
      image: ['https://imgur.com/RlVPBuV.jpg', 'https://imgur.com/Q0WtlPl.jpg'],
      video: ['https://www.youtube.com/embed/obPJVdUY6qo?si=-mrglIDKaCom_Zsj'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/gRI4gPk.jpg',
      title: 'MAZE',
      author: '김현민, 김채원, 전호진, 박민아, 이건호',
      text: '익숙하지만 낯선 곳. 내가 알던 그곳이 아닌 곳. 꿈인지 현실인지도 알 수 없는 곳. 나 홀로 남겨진 공포의 미로, Dreamcore Maze.',
      instagram: [],
      image: ['https://imgur.com/fmBjmfp.jpg', 'https://imgur.com/8E66RRa.jpg'],
      video: ['https://www.youtube.com/embed/1Xmmr4LEECs?si=Lut-_D8Drk-GEqmh'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/yCBOWPU.jpg',
      title: 'OASIS EXPRESS',
      author: '김현지, 정해린, 소지은, 김수경, 박찬영',
      text: '기상 이변으로 모래로 뒤덮인 지구. 생존자들을 태운 기차 한 대가 끝없이 궤도를 달리고 있다. 빈민굴 같은 맨 뒤쪽의 꼬리칸과 달리 앞쪽칸은 호화로운 생활을 한다. 열차 안의 부조리를 느낀 당신은 앞쪽 칸을 거쳐 기관실을 장악하기로 한다. 기관실로 이동해 기차 전체를 해방시켜라.',
      instagram: [],
      image: ['https://imgur.com/EvafVVq.jpg', 'https://imgur.com/EvafVVq.jpg'],
      video: ['https://www.youtube.com/embed/9v2qvuFQwcg?si=mwZyAi-co3NJEOHm'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/zdsvOqc.jpg',
      title: 'OVER 7F',
      author: '노민희, 최승민, 박서영, 양채윤, 변우영',
      text: '홍문관 7층. 이곳은 학생들이 끊임없이 밤을 지새우며 피워낸 열정이 묻어있는 특별한 공간입니다. 익숙한 풍경처럼 보이지만 문을 열면 그 너머로 일상과 환상이 어우러진 신비로운 세계가 펼쳐집니다. 세 가지 다른 공간에서 기묘한 운명을 함께할 세 명의 학생들을 만나보세요.',
      instagram: [],
      image: ['https://imgur.com/3NCek92.jpg', 'https://imgur.com/ppgFN2Q.jpg'],
      video: ['https://www.youtube.com/embed/djt4PWgvUIU?si=Ae3MH7OiHsAwvz7z'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/DShiDyX.jpg',
      title: '스텔라 어드벤처',
      author: '최예진, 김도영, 김민하, 맹지연, 최종원',
      text: '마을 이곳저곳을 날아다니며 간절한 소원을 비는 사람들의 소원을 이루어주는 스텔라. 그러나 악의 힘에 의해 그 신성한 힘을 빼앗기고 만다. 마을을 돌아다니며 도움이 필요한 주민들을 찾아 문제를 해결하고 힘을 모아 빼앗긴 힘을 되찾자!',
      instagram: [],
      image: ['https://imgur.com/JG6Uqu6.jpg', 'https://imgur.com/QftKULc.jpg'],
      video: ['https://www.youtube.com/embed/R0ArrTLC_aI?si=v4Ty3A0TF6s6VmQW'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/jcUMMHe.jpg',
      title: 'The Resistance',
      author: '구한나',
      text: '안드로이드가 인간을 지배하는 디스토피아적인 시대. 자유를 찾기 위해 레지스탕스에 들어가게 되고, 그 곳에서 동료들을 만난다. 각성하여 인간들을 해방시키고 인간 해방 운동을 벌이는 레지스탕스의 리더로서 혁명을 이끌게 된다.',
      instagram: [],
      image: ['https://imgur.com/eqbyPh1.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/T7uXyb3.jpg',
      title: 'Revive',
      author: '김유은',
      text: '숨겨진 고대 신전, 탐욕에 눈이 먼 낯선 침입자가 잠들어 있는 그녀를 깨워버렸다.',
      instagram: [],
      image: ['https://imgur.com/8WiIIiH.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/qOUcPuj.jpg',
      title: 'Holiday',
      author: '김현민',
      text: '1960년대 영국 런던. 바쁜 일상생활 중 찾아온 달콤한 휴일. 아끼는 코트를 입고 좋아하는 커피를 마시며 산책을 하면 일주일의 피로가 풀리는 기분이 든다!',
      instagram: [],
      image: ['https://imgur.com/4GvmA52.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/Wt0bEZn.jpg',
      title: 'Splatoon',
      author: '이민경',
      text: 'SPLAT your color! 시네마 4D(C4D)를 활용해 게임 ‘스플라툰’을 모티브로 하여 모션 시퀀스를 제작하였습니다.',
      instagram: ['k1rk1v'],
      image: ['https://imgur.com/JZAIxq1.jpg', 'https://imgur.com/eGP9yps.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/bJd1JgM.jpg',
      title: 'Late for School',
      author: '김민하',
      text: 'Maya를 활용해 기본 워킹 애니메이션을 응용한 동작으로 스토리가 있는 애니메이션을 만들었습니다. 첫번째 동작은 학교로 늦어 뛰어가는 워킹 동작, 두번째 동작은 소리가 안 들리게 살금살금 걸어가는 워킹 동작, 세번째 동작은 시선을 안 끌도록 교실로 들어가는 워킹 동작입니다.',
      instagram: ['ashkm237'],
      image: [
        'https://imgur.com/Y8yWd9D.jpg',
        'https://imgur.com/D2wbc3B.jpg',
        'https://imgur.com/6kbQocy.jpg',
        'https://imgur.com/0JM9Y6d.jpg',
      ],
      video: ['https://www.youtube.com/embed/hRttvzLv-Ng?si=XtC3mmjN-663ttpv'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/ebbwP4P.jpg',
      title: 'Howl’s Moving Castle',
      author: '강보영, 권용희 외 2명',
      text: 'Unreal Engine, Maya, Substance Painter를 기반으로 영화 ‘하울의 움직이는 성’을 모티브로 하여 방을 제작했습니다.',
      instagram: ['boyoung115'],
      image: [
        'https://imgur.com/bJpHzcG.jpg',
        'https://imgur.com/RVRMsv2.jpg',
        'https://imgur.com/qA7izHg.jpg',
        'https://imgur.com/tjkzCUC.jpg',
        'https://imgur.com/10z0Ov2.jpg',
      ],
      video: ['https://www.youtube.com/embed/X-WdlvMbNoY?si=g6kxA9nt749J0x6F'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/OEjAzvp.jpg',
      title: '1단계',
      author: '아이레이 1단계 커리큘럼작',
      text: 'Maya를 이용해 기초 모델링과 화면 구성을 배우고 지정된 공간을 만들었습니다. 자신만의 개성이 담긴 1단계 분들의 작품을 감상해 보세요!',
      instagram: [],
      image: [
        'https://imgur.com/i03i7e2.jpg',
        'https://imgur.com/U2PWdIi.jpg',
        'https://imgur.com/deJAyYR.jpg',
        'https://imgur.com/fj24HCn.jpg',
        'https://imgur.com/eYdBFVh.jpg',
        'https://imgur.com/xY9pwxX.jpg',
        'https://imgur.com/X1Btw2v.jpg',
        'https://imgur.com/z0ia6Rq.jpg',
        'https://imgur.com/3RYLk8V.jpg',
        'https://imgur.com/SrdqbX6.jpg',
      ],
      video: [],
      link: [],
    },

    {
      thumbnail: 'https://imgur.com/mm1UCla.jpg',
      title: 'Epilogue',
      author: '조예봄, 최원정',
      text: '몇 년 동안의 고립과 단절의 팬데믹 기간을 끝내고 다시 새롭게 맞이하는 자유를 노래하다.',
      instagram: ['itsaileencho', 'wonjung_choi_'],
      image: [
        'https://imgur.com/rDsxsmw.jpg',
        'https://imgur.com/OVpQyWl.jpg',
        'https://imgur.com/uOXbfx5.jpg',
        'https://imgur.com/rATekx7.jpg',
        'https://imgur.com/9Czhtg4.jpg',
        'https://imgur.com/Lfc5Cko.jpg',
        'https://imgur.com/bVkfMjU.jpg',
        'https://imgur.com/h1cKft7.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/KPIM3hH.jpg',
      title: 'TIME LINE',
      author: '강보영',
      text: '우리들은 다들 자신만의 시간에서 살아가기 때문에 같은 공간에 있더라도 시차가 존재할 수 있다.',
      instagram: ['boyoung115'],
      image: [
        'https://imgur.com/LIYNg68.jpg',
        'https://imgur.com/ULlqcp1.jpg',
        'https://imgur.com/EGjJGbw.jpg',
        'https://imgur.com/dPFefAc.jpg',
        'https://imgur.com/OhUPkYB.jpg',
      ],
      video: ['https://www.youtube.com/embed/la6S6brUpak?si=XiGyVSTYHeVej6ZUs'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/gFyRA7R.jpg',
      title: 'Time Paradox',
      author: '권용희',
      text: '과거와 미래를 동시에 추구하는 이질적인 공간. 그 속에서 현대의 흐름을 느낄 수 있다.',
      instagram: [],
      image: ['https://imgur.com/Ns9vTcI.jpg', 'https://imgur.com/zx4qaUk.jpg', 'https://imgur.com/gtu8Vuc.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/UFsK32N.jpg',
      title: 'Time Limit',
      author: '이휘성',
      text: '현대사회에서 우리들은 “시간 세상”에 얽매여 살아가는 듯하다.',
      instagram: [],
      image: ['https://imgur.com/kHfyKWt.jpg', 'https://imgur.com/kHfyKWt.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/lXg5Htb.jpg',
      title: 'The Doctor',
      author: '구한나',
      text: '세상이 위험에 빠졌을 때 누구나 하는 일. 닥터를 부른다.',
      instagram: [],
      image: ['https://imgur.com/XLaUNkk.jpg', 'https://imgur.com/x0syW9v.jpg', 'https://imgur.com/vquzf6r.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/p9Nt6z3.jpg',
      title: 'plant ARchives',
      author: '아이레이 서브프로젝트 단체작업',
      text: '아이레이 부원들이 발견한 가상의 식물들. 각자 연구를 통해 3D로 구현해 낸 식물들을 AR을 통해 현실 세계에서도 관찰할 수 있도록 선보입니다.',
      instagram: [],
      image: [
        'https://imgur.com/M1UIBWn.jpg',
        'https://imgur.com/JYULcXG.jpg',
        'https://imgur.com/bfd5wkj.jpg',
        'https://imgur.com/mSQwhMy.jpg',
        'https://imgur.com/YBQWR3L.jpg',
        'https://imgur.com/46OZEZo.jpg',
        'https://imgur.com/IYs8JPA.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/fsw64Eb.jpg',
      title: 'Merry Christmas with I-RAY',
      author: '아이레이 서브프로젝트 단체작업',
      text: '크리스마스를 맞이하여 산타 가오리가 선물을 들고 찾아왔습니다. 산타 가오리와 아이레이 부원들이 준비한 오너먼트와 선물들을 하나씩 열어보세요!',
      instagram: [],
      image: [
        'https://imgur.com/AsmjjxW.jpg',
        'https://imgur.com/wY3IpFt.jpg',
        'https://imgur.com/PzeWsuG.jpg',
        'https://imgur.com/jscHUIS.jpg',
        'https://imgur.com/KedgIE4.jpg',
        'https://imgur.com/LmQfuWS.jpg',
        'https://imgur.com/t364KWs.jpg',
        'https://imgur.com/OZ5UBUe.jpg',
        'https://imgur.com/EdS3TNW.jpg',
        'https://imgur.com/wn5a5Pb.jpg',
        'https://imgur.com/LR8Hrev.jpg',
        'https://imgur.com/eK3PubN.jpg',
        'https://imgur.com/LfrMy1t.jpg',
      ],
      video: [],
      link: [],
    },
  ],
  [
    // 야즈
    {
      thumbnail: 'https://imgur.com/HhueyYC.jpg',
      title: 'doomcore',
      author: '강민서',
      text: '이트륨, 산소, 우라늄, 텅스텐, 산소, 질소',
      instagram: ['mxraki___'],
      image: [
        'https://imgur.com/ZJMaawB.jpg',

        'https://imgur.com/N1IpsH5.jpg',
        'https://imgur.com/KvgOxaX.jpg',
        'https://imgur.com/ZHLYHxL.jpg',
        'https://imgur.com/YZeWk0M.jpg',
        'https://imgur.com/b53Yno7.jpg',
        'https://imgur.com/MtlR0H3.jpg',
        'https://imgur.com/XioRCHr.jpg',
      ],
      video: [],
      link: ['https://drive.google.com/file/d/1hjYQIbXnxGDkykPQXXEXDgOS-4MDi3Dx/view?usp=share_link'],
    },
    {
      thumbnail: 'https://imgur.com/eMSdkgC.jpg',
      title: '낯선',
      author: '고다현',
      text: '우리는 사물을 볼 때, 그 사물의 대표적인 이미지에 집중한다. 하지만 소소한 요소에 집중해보면 어떤 일이 일어날까?',
      instagram: ['da.hynue'],
      image: [
        'https://imgur.com/SCl37Sc.jpg',
        'https://imgur.com/nqCabeO.jpg',
        'https://imgur.com/IbIuDXe.jpg',
        'https://imgur.com/vL1SqcM.jpg',
      ],
      video: [],
      link: ['https://readymag.website/u4090134160/4652766/'],
    },
    {
      thumbnail: 'https://imgur.com/F3rxoAP.jpg',
      title: '우리의 동화',
      author: '권민지',
      text: '누구나 마음 속에 테라리움 하나씩은 품고 있는 법이다. 당신의 이야기는 무엇일까?',
      instagram: ['mklcf_230621'],
      image: ['https://imgur.com/WI8GPd0.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/E2VN9g9.jpg',
      title: '정의 기록',
      author: '기가연',
      text: '함께하고 담아두다',
      instagram: [],
      image: ['https://imgur.com/QI7wk7a.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/ukKcn4D.jpg',
      title: '뿌리, 줄기, 꽃, 열매',
      author: '김서연',
      text: '나를 한 포기 기르며 보고 적어온 글자들. 그것은 어느새 볕이 잘 드는 베란다에 방치한 식물처럼 무성해졌다. 글 속의 나는 어떤 사람이었고 어떤 사람인가? 다시 돌아보면서, 기록을 단단히 감쌀 수 있는 외피를 그렸다.',
      instagram: ['coc39'],
      image: [
        'https://imgur.com/ufvzNol.jpg',
        'https://imgur.com/MiAOdZf.jpg',
        'https://imgur.com/FjlyVnH.jpg',
        'https://imgur.com/aIrbkKC.jpg',
        'https://imgur.com/v5qFq2s.jpg',
        'https://imgur.com/Ai6p6iB.jpg',
        'https://imgur.com/S4jrGA3.jpg',
      ],
      video: [],
      link: ['https://drive.google.com/file/d/1Y-6GLf2xJK1kBzSgexY94cVEoRHro2Hx/view?usp=sharing'],
    },
    {
      thumbnail: 'https://imgur.com/UGjZspq.jpg',
      title: 'Consequence of Nothing',
      author: '김예영',
      text: '그 가게에서 훔치라고 했잖아!! 그게 뭐 어때서?!! 답 없는 ZERO와 이상한 PLUSHIE 의 만남 그리고 결과',
      instagram: ['swinreflect_art'],
      image: ['https://imgur.com/5f3a2fX.jpg', 'https://imgur.com/PmN1Xj8.jpg'],
      video: ['https://www.youtube.com/embed/vb8k70dWEuI?si=fcYNPZQ3asKjdkbP'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/ZX9PWKf.jpg',
      title: '꽃새와 나무둥지',
      author: '김정혜',
      text: '서로에게 새와 둥지가 되어주는 꽃과 나무가 있었습니다. 둘은 쑥쑥 자라서 무엇이 될까요?',
      instagram: ['jhyeye_'],
      image: [
        'https://imgur.com/Xu9oQQh.jpg',
        'https://imgur.com/Fg2QcnY.jpg',
        'https://imgur.com/M6LcP88.jpg',
        'https://imgur.com/RXCymgy.jpg',
        'https://imgur.com/Fh6SQr7.jpg',
        'https://imgur.com/ATsE9FR.jpg',
        'https://imgur.com/3CxLpbQ.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/fPMY6Rj.jpg',
      title: '저 끝에 있는 물품 보관소\r\nLost-and-Found of the End',
      author: '김지호',
      text: '어느 날, 아주 작은 틈새 사이로 지우개 하나가 통 통 통... 떨어졌어요. 그곳은 잃어버린 물건들이 모인 곳이었어요. 물건들은 주인을 기다리며 각자만의 기억을 보관하고 있답니다. 당신은 까먹었을지도 모르는 아주 작고 소중한 기억을 볼 수 있지요. 귀엽고 자그마한 지우개와 함께 물품 보관소로 한 번 떠나볼까요?',
      instagram: ['what_about_jho'],
      image: [
        'https://imgur.com/DPT715K.jpg',
        'https://imgur.com/PXls6Fz.jpg',
        'https://imgur.com/kyyMGtJ.jpg',
        'https://imgur.com/oCRle1T.jpg',
        'https://imgur.com/9lItoc7.jpg',
        'https://imgur.com/VsoLxKd.jpg',
        'https://imgur.com/aWUG2Tj.jpg',
        'https://imgur.com/vLpXZbf.jpg',
        'https://imgur.com/8LH2sx9.jpg',
        'https://imgur.com/Go1iQbK.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/0ElnECI.jpg',
      title: '이에르',
      author: '류정현',
      text: '아, 우린 달라서 하나가 될 수 있구나',
      instagram: ['ryuu._.j'],
      image: [
        'https://imgur.com/LoHWhSL.jpg',
        'https://imgur.com/zfwKJZ9.jpg',
        'https://imgur.com/sHp1HSH.jpg',
        'https://imgur.com/zPhOkxG.jpg',
      ],
      video: ['https://www.youtube.com/embed/yqlMt5sGPsg?si=t2dKOtediElwon6_'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/Mjc1gpF.jpg',
      title: 'Only for you : Glass House',
      author: '민아영',
      text: '당신만을 위한 패션, 당신만을 위해 키운 꽃. 지금 여기, 글래스 하우스에서.',
      instagram: ['a_03mmmm'],
      image: [
        'https://imgur.com/0ACpAhb.jpg',
        'https://imgur.com/qBRQanL.jpg',
        'https://imgur.com/qpoai3p.jpg',
        'https://imgur.com/ShnRMgG.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/USjfdcU.jpg',
      title: '불면증',
      author: '민지원',
      text: '비현실적인 상상은 숙면에 도움이 됩니다',
      instagram: ['erum_binn'],
      image: ['https://imgur.com/8UhjtDM.jpg', 'https://imgur.com/A6UWppo.jpg', 'https://imgur.com/Uu7kzg5.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/7tPlrYS.jpg',
      title: '식물랩소디 (Sik-mul Rhapsody)',
      author: '박서영',
      text: '그들의 노래에 귀 기울여 보세요!',
      instagram: ['meego.club'],
      image: [
        'https://imgur.com/XNtWtB5.jpg',
        'https://imgur.com/X5gshXr.jpg',
        'https://imgur.com/nFXfknM.jpg',
        'https://imgur.com/tFeEds4.jpg',
        'https://imgur.com/0VSVfca.jpg',
        'https://imgur.com/yDOiNl0.jpg',
        'https://imgur.com/eMpDwRE.jpg',
        'https://imgur.com/bq7cuCP.jpg',
        'https://imgur.com/l1xoV31.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_thumbnail_parktaeyeon.jpg',
      title: 'LILIPIN',
      author: '박태연',
      text: 'parvus onus magnus',
      instagram: ['taeynprk'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_parktaeyeon_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_parktaeyeon_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_parktaeyeon_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_parktaeyeon_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_parktaeyeon_5.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/sUsOMMx.jpg',
      title: 'Beads Embriodery',
      author: '배수연',
      text: '내가 사랑하는 색상과 조각을 모두 담았어요..',
      instagram: ['wrkgby'],
      image: ['https://imgur.com/kN6S4lb.jpg', 'https://imgur.com/JXjvZdW.jpg', 'https://imgur.com/jgKbAQi.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/GqYMDPQ.jpg',
      title: '온실 속 칵테일 바',
      author: '배초은',
      text: '온실 속의 칵테일 바에는 어떤 사람이 찾아올까요. 선택의 이유는 무엇이고, 무슨 생각을 하고 계신가요?',
      instagram: ['altnpr41'],
      image: [
        'https://imgur.com/FsXXOVj.jpg',
        'https://imgur.com/0AhujvP.jpg',
        'https://imgur.com/OynolDB.jpg',
        'https://imgur.com/XoVwoTs.jpg',
        'https://imgur.com/cMmbb2O.jpg',
        'https://imgur.com/0Ln3BHF.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/tO1jvSF.jpg',
      title: '여행을 떠나요',
      author: '부문희',
      text: '어디든 갈 수 있고 뭐든지 될 수 있어!',
      instagram: ['boooomoonhee'],
      image: ['https://imgur.com/Ylic8WH.jpg', 'https://imgur.com/IuXQT8a.jpg', 'https://imgur.com/58eVmzK.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/tb9emDs.jpg',
      title: 'Photosynthesis',
      author: '서재상',
      text: 'Internet living',
      instagram: ['seo__jason'],
      image: ['https://imgur.com/c6BCiyx.jpg', 'https://imgur.com/tWUV3Nj.jpg'],
      video: ['https://www.youtube.com/embed/NCndUwquEXk?si=uhQw_1J28GYL-XjE'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/kZGzI0Q.jpg',
      title: '기억',
      author: '송윤하',
      text: '이 데이터는 비밀과학연구기관 FRO에서 오랜 기간 분석한 생명체의 기억 더미로, 현재 일부 내용만 복구에 성공했습니다.',
      instagram: ['yunha_painting'],
      image: ['https://imgur.com/TJCKaWI.jpg'],
      video: ['https://www.youtube.com/embed/oV5p3H5v9LE?si=RClvXl621C4OTKvm'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/jEtebLq.jpg',
      title: '순정(純情)',
      author: '신혜영',
      text: '오랫동안 간직할 수 있기를 바라며 건네는 작은 편지. 순수함은 금방 바래기 마련이다. 서툴지만 온전한 진심을 들여다보기, 마음을 인정하고 간직하기. 마침내 순정은 아름다운 열매를 꽃피운다.',
      instagram: ['shine.y0'],
      image: [
        'https://imgur.com/giNvqmz.jpg',
        'https://imgur.com/FQV4bwv.jpg',
        'https://imgur.com/sLsTGLm.jpg',
        'https://imgur.com/AaeieaB.jpg',
        'https://imgur.com/S5czNiO.jpg',
        'https://imgur.com/bGAEeeb.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/VIpZWbt.jpg',
      title: '온실',
      author: '심준섭',
      text: '온실 속에서 나와',
      instagram: ['shimjseob'],
      image: ['https://imgur.com/cRGnTe6.jpg', 'https://imgur.com/3uFFmzr.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/K3HqsqA.jpg',
      title: '당신 생태계 도감\r\nA guide to your ecosystem',
      author: '오다은',
      text: '여기, 당신이라는 하나의 우주를 찾아온 관찰자가 있다.',
      instagram: ['eightdegreec'],
      image: ['https://imgur.com/HxY5lJb.jpg', 'https://imgur.com/U4E8ug4.jpg', 'https://imgur.com/1rgmHFv.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_thumbnail_yuhyeeyeon.jpg',
      title: '모험가 Adventurer',
      author: '유희연',
      text: '유일한 유토피아에서 단 한 명이 떠나야만 한다. 그리고 나는 그를 기록해야 한다.',
      instagram: ['yuyuyeon_'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_8.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_9.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yuhyeeyeon_10.jpg',
      ],
      video: [],
      link: ['https://posty.pe/qmt6eq'],
    },
    {
      thumbnail: 'https://imgur.com/LGtTMb8.jpg',
      title: '비약과 예외, 큰뜻의 상실',
      author: '이경민',
      text: '깊은 뜻을 가져야만 작업이 의미를 가질 수 있다는 강박에서 벗어나기. 스스로 세운 감옥에서 탈출하고자 버둥거린 흔적의 일부. 그러나 가만 생각해 보자, 지금까지의 작업에 있어 자신에게 아무런 의미도 갖지 않는 작업을 해본 적이 있던가? 사실은 나 자신을 향한 허울뿐인 질타가 아니었던가? 스스로를 향한 불신은 곧 보이지 않는 쇠창살이 된다.',
      instagram: ['0R5V0R'],
      image: [
        'https://imgur.com/8eRwkDw.jpg',
        'https://imgur.com/3ng3gcl.jpg',
        'https://imgur.com/JFNf1TE.jpg',
        'https://imgur.com/WfjXHVy.jpg',
        'https://imgur.com/An6ie4t.jpg',
        'https://imgur.com/E3xiiSE.jpg',
        'https://imgur.com/gJmjZlc.jpg',
        'https://imgur.com/17gWrjK.jpg',
        'https://imgur.com/ICYMOlV.jpg',
      ],
      video: [],
      link: ['https://drive.google.com/file/d/1n4QsNg5CMfghlHp7-VDQracSU7A-bN0s/view?usp=sharing'],
    },
    {
      thumbnail: 'https://imgur.com/UtEs2cy.jpg',
      title: '존재를 위해 존재하는 것들',
      author: '이민지',
      text: '안에 있는 것을 보호하기 위해 존재하는 것들이 있다. 한 존재가 고유함을 지키고 살아갈 수 있는 것은 그 겉을 감싸고 있는 질기고 단단한 껍질 덕분이다. 우리에게는 어떤 껍질이 있을까.',
      instagram: ['lleeminj'],
      image: [
        'https://imgur.com/AKyXnft.jpg',
        'https://imgur.com/7hJodre.jpg',
        'https://imgur.com/LCpCgfm.jpg',
        'https://imgur.com/gYUQ7ro.jpg',
        'https://imgur.com/GIYSGqf.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_thumbnail_yisongeun.jpg',
      title: '청룡제과',
      author: '이송은',
      text: '청룡제과만의 특별한 빵과 과자를 즐기시길 바랍니다.',
      instagram: ['song_y_song'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_6.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_7.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_8.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_9.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/yadz_yisongeun_10.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/sQFAlPQ.jpg',
      title: '설원에서 : In the Snowfield',
      author: '임유진',
      text: '고립된 마을과 설원 속을 오가는 이틀간의 이야기',
      instagram: ['sinsan_543'],
      image: [
        'https://imgur.com/4XbkoZe.jpg',
        'https://imgur.com/qIImE8r.jpg',
        'https://imgur.com/O3Gfyca.jpg',
        'https://imgur.com/0ziF9vQ.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/BbPeEOD.jpg',
      title: '드림 플랜테어리',
      author: '정경윤',
      text: '딸-랑. 어서오세요! 꿈을 이뤄드리는 식물의 님프를 판매하는 Dream Plantary입니다. 마법같이 당신의 소원이 이뤄지길 바라시나요? 저희 상점에 들어온 아주 특별한 정령을 소개합니다! 식물의 생명과 신비한 기운을 머금고 태어난 이 정령은 약간의 재주를 이용해 우리들의 소망을 이뤄줍니다.',
      instagram: ['kyungyun_id'],
      image: [
        'https://imgur.com/2zDet0G.jpg',
        'https://imgur.com/LktzgfR.jpg',
        'https://imgur.com/xg4EY6G.jpg',
        'https://imgur.com/aN0opbT.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/GFvGAF2.jpg',
      title: '결정화',
      author: '정재령',
      text: '당신의 결정이 아름다운 결정으로 자라길',
      instagram: ['jjr_piece'],
      image: [
        'https://imgur.com/Ge3Gt8g.jpg',
        'https://imgur.com/6C4oksR.jpg',
        'https://imgur.com/AImFIs8.jpg',
        'https://imgur.com/ynxIbR3.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/icNizg9.jpg',
      title: '해골물 곤충편',
      author: '조수민',
      text: '찬찬히 보면 다 예쁜 구석이 있어요..사람도 동물도. 보기 나름',
      instagram: ['imeaggaemi'],
      image: [
        'https://imgur.com/4BkzcKf.jpg',
        'https://imgur.com/3jA25I8.jpg',
        'https://imgur.com/0UuajbI.jpg',
        'https://imgur.com/Ir1WdAu.jpg',
        'https://imgur.com/TLV84Pz.jpg',
        'https://imgur.com/XD2sqAD.jpg',
        'https://imgur.com/CZ7Mcfk.jpg',
        'https://imgur.com/HV77lTY.jpg',
      ],
      video: [],
      link: [],
    },
  ],
  [
    // 애드레날린
    {
      title: '교보에서, 쉼(休)',
      author: '김민서',
      text: '바쁘고 바쁜 현대 사회, 사람들의 지친 몸과 마음의 힐링공간이 될 수 있는 교보문고.\n함께 교보에서의 따뜻한 시간을 보내봅시다.',
      instagram: ['4rc.enciel_'],
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_thumbnail_kimminseo.jpg',
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_kimminseo_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_kimminseo_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_kimminseo_3.jpg',
      ],
      video: [],
      link: ['https://4rc-enciel3-48888.waveon.me/pages/22'],
    },
    {
      title: "Beard Papa's",
      author: '김윤수',
      text: 'Fresh and Natural Cream Puffs!\n일본에서 시작한 비어드 파파는 전세계에서 팔리는 슈크림 전문 체인점 입니다. 현재 한국에서 관심도가 높지가 않아서, 비어드 파파의 슈크림을 더 알리기 위해 리브랜딩 또는 광고 작업을 했습니다.',
      instagram: ['yoonsuuuu'],
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_thumbnail_KimYoonsu.jpg',
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_KimYoonsu_1.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_KimYoonsu_2.jpeg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_KimYoonsu_3.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_KimYoonsu_4.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_KimYoonsu_5.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_KimYoonsu_6.jpg',
      ],
      video: ['https://www.youtube.com/embed/SUaM0GIQiF4?si=xg4WZ1w_vPAv53w4'],
      link: [],
    },
    {
      title: 'Colorize Kodak',
      author: '박세진',
      text: 'Colorize Kodak은 코닥의 색채로 가득 채워나가는 과정입니다. 디지털의 발전과 함께 코닥은 새로운 가치를 창출하는 길을 모색합니다.',
      instagram: ['ribbemee'],
      thumbnail: 'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_thumbnail_parksejin.jpg',
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_parksejin_1.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_parksejin_2.jpg',
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/adrenalin_parksejin_3.jpg',
      ],
      video: [],
      link: [],
    },
    {
      title: "Hi, I'm Kristin:)",
      author: '박소민',
      text: '하파크리스틴은 당신이 인생 렌즈를 찾을 수 있도록 새로운 컬러와 패턴을 매일 연구하고 있습니다. 크리스틴과 친구가 되어 나에게 빛나는 오늘의 눈동자를 선물해 보세요!',
      instagram: ['sparkqkrth'],
      thumbnail: 'https://imgur.com/G1Mrr6M.jpg',
      image: [
        'https://imgur.com/RyNHApz.jpg',
        'https://imgur.com/2siss4l.jpg',
        'https://imgur.com/hoP7b03.jpg',
        'https://imgur.com/mmXQAOC.jpg',
        'https://imgur.com/aWAqqeo.jpg',
        'https://imgur.com/eY404jg.jpg',
        'https://imgur.com/tuapuTZ.jpg',
        'https://imgur.com/KGIczM0.jpg',
        'https://imgur.com/EI1FIno.jpg',
        'https://imgur.com/AGVyHKZ.jpg',
      ],
      video: [],
      link: [],
    },
    {
      title: 'Crocs Bath',
      author: '백신영',
      text: '물이 닿는 곳이라면 어디든 크록스와 함께하자. 당신의 여정을 함께할 첫번째 시리즈를 소개한다!',
      instagram: ['sinyxxng_'],
      thumbnail: 'https://imgur.com/h8xfIEE.jpg',
      image: [
        'https://imgur.com/1VHONBn.jpg',
        'https://imgur.com/Dq6lka0.jpg',
        'https://imgur.com/B19gRqI.jpg',
        'https://imgur.com/j3ERk6n.jpg',
        'https://imgur.com/K99eN2u.jpg',
      ],
      video: ['https://www.youtube.com/embed/sKt5XihkBHs?si=6MNprjq2UwCrHqYe'],
      link: [],
    },
    {
      title: '공연 산책을 위한 최고의 공원,\r\n인터파크!',
      author: '서가은',
      text: '공연의 중심지 대학로! 인터파크에서 먼저 산책해보시는 건 어떤가요? 보다 즐거운 산책로로 새롭게 단장된 인터파크가 당신을 초대합니다.',
      instagram: ['rkdms_sge'],
      thumbnail: 'https://imgur.com/OCc633J.jpg',
      image: [
        'https://imgur.com/P5vPpyB.jpg',
        'https://imgur.com/kkulo0R.jpg',
        'https://imgur.com/2v5KBcf.jpg',
        'https://imgur.com/LVo8Y9t.jpg',
        'https://imgur.com/2UIfzhV.jpg',
        'https://imgur.com/p48xknn.jpg',
        'https://imgur.com/JbpBiwn.jpg',
        'https://imgur.com/jKYYWLt.jpg',
        'https://imgur.com/I9NqIYT.jpg',
        'https://imgur.com/n4OXpli.jpg',
      ],
      video: [],
      link: [
        'https://www.figma.com/proto/tvPkAezrEzz8y3CFUh5QjC/%EC%9D%B8%ED%84%B0%ED%8C%8C%ED%81%AC%ED%8B%B0%EC%BC%93?node-id=0-1',
      ],
    },
    {
      title: '香饗 ; [香(향기 향) / 饗(잔치할 향)]',
      author: '엄소연',
      text: "인센스 브랜드 나그참파를 향의 향연, '향향'을 컨셉으로 광고를 제작했다.",
      instagram: ['soynidl'],
      thumbnail: 'https://imgur.com/imyYUlk.jpg',
      image: ['https://imgur.com/FzrH2k8.jpg', 'https://imgur.com/gkgdXoZ.jpg', 'https://imgur.com/t4LLYTb.jpg'],
      video: [],
      link: [],
    },
    {
      title: 'Amuse in Beanland',
      author: '장지윤',
      text: '어뮤즈만의 비건 콩 핸드크림의 세계로 당신을 초대합니다.',
      instagram: ['wlokjzip'],
      thumbnail: 'https://imgur.com/e9A2G1I.jpg',
      image: [
        'https://imgur.com/oPso8f2.jpg',
        'https://imgur.com/BYlsrIe.jpg',
        'https://imgur.com/UxthOl8.jpg',
        'https://imgur.com/UVGzM5x.jpg',
        'https://imgur.com/8b7eMXh.jpg',
        'https://imgur.com/iE1tWJ9.jpg',
        'https://imgur.com/4rhTt70.jpg',
        'https://imgur.com/rwKakw9.jpg',
        'https://imgur.com/Tnn2GGc.jpg',
      ],
      video: [],
      link: [],
    },
    {
      title: 'Sweet Home with SLEEPYCAT',
      author: '정유라',
      text: '당신의 삶에 달콤함 한 스푼 더해줄 슬리피캣 파자마를 소개합니다.',
      thumbnail: 'https://imgur.com/bX16cEn.jpg',
      instagram: [],
      image: ['https://imgur.com/b6SPQMV.jpg', 'https://imgur.com/rnbTP72.jpg', 'https://imgur.com/s3YHCB0.jpg'],
      video: [],
      link: [],
    },
    {
      title: 'We eat with weeat',
      author: '최예린, 최유진',
      text: 'Delight your lunch time!\r\n위잇은 건강하지 못한 식습관을 가진 사람들에게 식사가 즐거워지는 순간을 만들며 건강한 삶으로 이끄는 식습관 파트너입니다.',
      instagram: ['yeriels2', 'coeyujin521'],
      thumbnail: 'https://imgur.com/gWyzLmI.jpg',
      image: [
        'https://imgur.com/ipf9jMV.jpg',
        'https://imgur.com/NPH7iEZ.jpg',
        'https://imgur.com/2Ifpchr.jpg',
        'https://imgur.com/YJQh7T3.jpg',
        'https://imgur.com/ZQYpCno.jpg',
        'https://imgur.com/U82DlQr.jpg',
        'https://imgur.com/jwXXfHp.jpg',
        'https://imgur.com/ocHBGRK.jpg',
        'https://imgur.com/zgENkda.jpg',
      ],
      video: [],
      link: [
        'https://www.figma.com/proto/PgSC6uBuUq5rq3G9jPVUUn/we-eat-with-weeat?page-id=0%3A1&type=design&node-id=1-4&viewport=825%2C376%2C0.45&t=TjaBas2ihH7gpuJW-1&scaling=scale-down-width&starting-point-node-id=1%3A4&mode=design',
      ],
    },
    {
      title: '에이쁠 와쁠',
      author: '최윤영',
      text: '에이쁠 와쁠은 와플대학의 모든 것을 담은 공간입니다. 와플대학의 신입생이 될 당신을 기다립니다!',
      instagram: ['po2sh1p'],
      thumbnail: 'https://imgur.com/lostMbR.jpg',
      image: ['https://imgur.com/nYafNVM.jpg', 'https://imgur.com/FAgJwcn.jpg', 'https://imgur.com/9Cfg31k.jpg'],
      video: [],
      link: [],
    },
    {
      title: 'LAMY is not just a black.',
      author: '최혜림',
      text: '우리의 잉크는 그저 그런 검은색이 아닙니다. 수만은 개성이 함축된 LAMY만의 검은색으로 당신을 표현하세요.',
      instagram: ['mickandey'],
      thumbnail: 'https://imgur.com/K5iKm8Q.jpg',
      image: [
        'https://imgur.com/drkrwum.jpg',
        'https://imgur.com/Zfo0MzA.jpg',
        'https://imgur.com/47gxGEI.jpg',
        'https://imgur.com/68Xs97S.jpg',
      ],
      video: [],
      link: [],
    },
  ],
  //프로토
  [
    {
      thumbnail: 'https://imgur.com/bE5TiDu.jpg',
      title: 'Grabbox',
      text: '〈그랩박스〉에서 잠깐 필요한 제품은 집고, 안 쓰는 제품은 보관해주세요. 지갑과 지구 모두를 아낄 수 있답니다.',
      instagram: [],
      author: '강유성',
      image: ['https://imgur.com/PXHHHon.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/7STCAxf.jpg',
      title: 'Snow Falls',
      text: '눈 오는 설원. 수많은 사람들이 눈에 흔적을 남기며 지나간다. 하지만 그 흔적은 잠시 뿐이고, 끝에는 원래의 눈 쌓인 모습으로 돌아온다. 시간은 흐른다. 모든 것은 지나간다. 아팠던 기억은 흐려지고 삶은 계속 진행된다. 눈이 내리고, 눈 덮이듯이. 시련은 설원에 묻어두고 앞으로 나아가자.',
      author: '권수민',
      image: [
        'https://imgur.com/0P325GR.jpg',
        'https://imgur.com/xBbIVA6.jpg',
        'https://imgur.com/IMnlZMQ.jpg',
        'https://imgur.com/EoKMfbh.jpg',
        'https://imgur.com/1YlXK42.jpg',
        'https://imgur.com/9JtbAqY.jpg',
        'https://imgur.com/z5BNPji.jpg',
        'https://imgur.com/SlDyzEY.jpg',
      ],
      video: [],
      link: [],
      instagram: ['lovlyout', 'minjeongwonn'],
    },
    {
      thumbnail: 'https://imgur.com/SO1XWRm.jpg',
      title: '빈 껍데기 장식 방지',
      text: '애벌레가 이미 죽은 번데기를 치장하는 행위를 단절하고자 글자장식들을 연구한 후, 이를 기반으로 AR과 책을 만들었다.',
      author: '김세은',
      image: [
        'https://imgur.com/8mVexav.jpg',
        'https://imgur.com/m1oNdeQ.jpg',
        'https://imgur.com/k6UxMoT.jpg',
        'https://imgur.com/ZH81cCm.jpg',
      ],
      video: [],
      link: ['https://kimseeunse.github.io/Chrysalis/'],
      instagram: ['kimseeunse', 'meungse'],
    },
    {
      thumbnail: 'https://imgur.com/ojpyPdR.jpg',
      title: 'Forbidden',
      text: '우리는 모두 금단의 과일을 한 입 먹고 싶어하지. 〈Forbidden〉은 먹으면 선악을 알게 된다는 선악과 나무의 열매로 인간을 유혹한다.',
      author: '김하민',
      image: ['https://imgur.com/eyWkUVK.jpg', 'https://imgur.com/5JGjbjH.jpg'],
      video: [],
      link: [],
      instagram: ['mint_1ia'],
    },
    {
      thumbnail: 'https://imgur.com/v813RPg.jpg',
      title: 'MOTI',
      text: '보기만 해도 귀찮고 지긋지긋한 가계부 쓰기! 모티와 대화하며 가계부를 간단하게 확인해보면 어떨까요? 채팅형 가계부 모티가 매일매일의 소비를 채팅으로 가볍게 전달해드릴게요.',
      author: '배은환, 정나명',
      image: ['https://imgur.com/UcwfBiM.jpg'],
      video: [],
      link: ['https://www.behance.net/gallery/193007043/MOTI-Chat-driven-finance-management-service'],
      instagram: ['ring17ring', 'hnmy_ii'],
    },

    {
      thumbnail: 'https://imgur.com/yUJCkd4.jpg',
      title: '신체편집샵',
      text: '〈신체 편집샵〉에 오신 걸 환영합니다! 몸이 마음에 안 든다고요? 굳어진 승모근, 너덜거리는 손목, 욱신거리는 허리… 모두 새것으로 교체하고 싶다고요? 신체 편집샵에서는 모두 가능하답니다~ 원하는 부위를 구매하고 새로 갈아끼우세요!',
      author: '신유안',
      image: [
        'https://imgur.com/H0hfFGQ.jpg',
        'https://imgur.com/DR6rmbn.jpg',
        'https://imgur.com/crDi6en.jpg',
        'https://imgur.com/qlkz9Hv.jpg',
      ],
      video: [],
      link: ['https://readymag.website/u3929919061/welcometothebodyshop/'],
      instagram: ['nuttellawaffle', 'yyyouannn'],
    },
    {
      thumbnail: 'https://imgur.com/fdvuREN.jpg',
      title: 'The Red Shoes',
      text: '동화 “The Red Shoes” 그리고 동명 영화를 기반으로 스토리를 재구성하며 표현합니다.',
      author: '안유진',
      image: [
        'https://imgur.com/I6x8ZBN.jpg',
        'https://imgur.com/m49urwG.jpg',
        'https://imgur.com/tEJiJTK.jpg',
        'https://imgur.com/POjZYr8.jpg',
        'https://imgur.com/HUBT1gC.jpg',
      ],
      video: ['https://www.youtube.com/embed/XijI73P1mrE?si=F3jr-Rzmo1P32a8h'],
      instagram: ['yoozeany'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/x0vut87.jpg',
      title: '세상에서 제일(ONE-DAY)',
      text: '〈세상에서 제일〉 원 데이 클래스에 여러분을 초대합니다. 이번 클래스에서는 〈세상에서 제일〉이라는 타이틀 아래 초월적이고 강렬한 이미지와 존재를 제작하는 노하우를 가르쳐 드려요. *주의할 점은 모든 것은 상대적이라는 사실.',
      author: '안재민',
      image: [
        'https://imgur.com/4dUliZl.jpg',
        'https://imgur.com/lPgCx4r.jpg',
        'https://imgur.com/qTEmioB.jpg',
        'https://imgur.com/cJS1fCo.jpg',
      ],
      video: [],
      link: [],
      instagram: ['anjaemiseoyo'],
    },
    {
      thumbnail: 'https://imgur.com/MzeyDe1.jpg',
      title: '렌즈-2(Lens-2)',
      text: '인간의 눈 뒤에는 사실 하나의 렌즈가 더 존재합니다. 이 프로그램은 렌즈-2의 작동방식을 간접적으로 체험할 수 있도록 기획되었습니다.',
      author: '유민서',
      image: [
        'https://imgur.com/267kfPs.jpg',
        'https://imgur.com/fLgRBz4.jpg',
        'https://imgur.com/byr7uxi.jpg',
        'https://imgur.com/itqTlYc.jpg',
        'https://imgur.com/uoWPhhZ.jpg',
      ],
      video: [],
      link: [],
      instagram: ['sirmeenew_works'],
    },
    {
      thumbnail: 'https://imgur.com/1s7n9iR.jpg',
      title: '사랑은 현실이야',
      text: 'Love Lecture',
      author: '윤희서',
      image: ['https://imgur.com/9X2HAn6.jpg', 'https://imgur.com/aQcIPqm.jpg'],
      video: [],
      link: [],
      instagram: [],
    },
    {
      thumbnail: 'https://imgur.com/EkEjKxe.jpg',
      title: 'Representation',
      text: '표상(= Representation)은 추상적이거나 드러나지 아니한 것을 구체적인 형상으로 나타냄을 의미합니다. 작품을 통하여 겉으로 드러나지 않고 소외당했던 현대적 난민에 대해 시각적 상호작용을 시도하고, 그 속에서 대중들과의 구상적인 소통이 이루어져 나타납니다.',
      author: '이민석',
      image: [
        'https://imgur.com/ieSQ7yH.jpg',
        'https://imgur.com/IbPu4uh.jpg',
        'https://imgur.com/62AsYol.jpg',
        'https://imgur.com/QuNp18b.jpg',
      ],
      video: [],
      link: [],
      instagram: [],
    },
    {
      thumbnail: 'https://imgur.com/raxiAs7.jpg',
      title: '우리 웹 게첩합니다',
      text: '아무도 현수막을 찾아서 보지 않는다. 이 웹 공간에서는 한 번 찾아-보자!',
      author: '이수민',
      image: [
        'https://imgur.com/Csn20fx.jpg',
        'https://imgur.com/DITZe3C.jpg',
        'https://imgur.com/H6kGkF5.jpg',
        'https://imgur.com/PFg7q0I.jpg',
        'https://imgur.com/FkEAP3R.jpg',
      ],
      video: [],
      link: ['https://soomandsoom.github.io/banner/'],
      instagram: ['s0omie', 'smywrkng'],
    },
    {
      thumbnail: 'https://imgur.com/UakARjU.jpg',
      title: 'Parrotmeter',
      text: '〈Parrotmeter〉는 아동 교육 프로그램으로, 사용자는 자연적인 진화와 인공적인 변화 사이의 차이를 통한 인간 욕망에 대한 결과를 마주합니다. 이를 통해, 자연 법칙에서 벗어나 인간의 유희로 만들어진 애완동물에 대한 고민과 성찰을 경험할 수 있습니다.',
      author: '이지윤',
      image: ['https://imgur.com/CfinLmc.jpg'],
      video: ['https://www.youtube.com/embed/4p1iSBh68kA?si=m_YbGy4rri8ojeaK'],
      instagram: ['atzzil_yoon'],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/xxKD3AX.jpg',
      title: '웹윅',
      text: '한 주마다 서로에게 ‘웹’이라는 매체가 지니는 의미에 대한 질문을 하고 답변합니다. 회의가 끝난 후 일주일 동안 대화의 주제를 관통하는 페이지를 만들어냅니다.',
      author: '전시은, 조희원',
      image: ['https://imgur.com/xxKD3AX.jpg'],
      video: [],
      link: [],
      instagram: ['zsiiun', 'h_tranquil_q'],
    },
    {
      thumbnail: 'https://imgur.com/MGI7CyC.jpg',
      title: '美來',
      text: '未來에서 美來로, 다가오는 미래는 새로운 형태의 아름다움을 제안합니다.',
      author: '전지연',
      image: [
        'https://imgur.com/MGI7CyC.jpg',
        'https://imgur.com/g2HAocg.jpg',
        'https://imgur.com/l0vWfog.jpg',
        'https://imgur.com/4PNE1Fb.jpg',
        'https://imgur.com/nQUaRWn.jpg',
        'https://imgur.com/MyUE4HQ.jpg',
        'https://imgur.com/2i60T0W.jpg',
        'https://imgur.com/iKjWxvP.jpg',
        'https://imgur.com/sphllQ8.jpg',
        'https://imgur.com/tlhLhCM.jpg',
      ],
      video: ['https://www.youtube.com/embed/uHzbwMc0CFU?si=F3oWLUtl8K-8erlg'],
      instagram: ['0esign_', 'delay_.j'],
      link: [],
    },

    {
      thumbnail: 'https://imgur.com/gQEM9Hb.jpg',
      title: 'Orbit',
      text: '자주 보지 못하더라도 마음은 닿을 수 있게! 안부 연락 서비스로 마음을 계속 이어나가세요.',
      author: '정윤서',
      image: [],
      video: [],
      link: [],
      instagram: ['yns.cresc'],
    },
    {
      thumbnail: 'https://imgur.com/dVaqb8f.jpg',
      title: '미(未)술관 Non Finito',
      text: '그림을 그리다 보면 붓을 떼고픈 기분이 들 때가 종종 있다. 선 하나가, 색 하나가 부족하기에 더 사랑스러운 것이다. 빚어내는 나 조차도 미완성인데 무언가를 완성할 수 있는 능력 따위 내게 없을지 모른다. 아름다움에 완(完)이 어디 있고, 자기표현에 끝이 어디 있는가.',
      author: '최지현',
      image: ['https://imgur.com/dVaqb8f.jpg'],
      video: [],
      link: [],
      instagram: ['zi0hyxn'],
    },
  ],

  [
    // 하이픈
    {
      thumbnail: 'https://imgur.com/FpXgR6i.jpg',
      title: 'seeku',
      author: '민솔, 전서현, 황예지',
      text: 'SEEK YOUR SECURITY, seeku\r\n\r\n디지털 서비스 이용약관, 무심코 동의하고 있지 않나요?\r\n당신이 개인정보 주도권을 되찾을 수 있도록 seeku가 함께 할게요.\r\n\r\nseeku는 당신을 위한 온라인 서비스 가입 과정 도우미예요.\r\n개인정보 약관을 당신의 상황에 맞추어 해석하고 개인정보 이용 과정을 추적하여\r\n지속적인 개인정보 관리환경을 만들어드릴게요.',
      instagram: ['s.ol_lala', 'shyun_u.u', 'hwangyeji__'],
      image: [
        'https://imgur.com/V4hMy63.jpg',
        'https://imgur.com/AEt7MyR.jpg',
        'https://imgur.com/91x5KLe.jpg',
        'https://imgur.com/xX0PXx9.jpg',
        'https://imgur.com/FZiav9Y.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/u7Fzfh3.jpg',
      title: 'Vi’near',
      author: '김민재, 김새하, 최선우',
      text: '우리는 타인에게 마음을 전하기 위해 선물을 자주 찾습니다.\r\n특히 와인은 부담스럽지 않으면서도 고급스럽게 마음을 표현할 수 있는 선물로 주목받고 있습니다. 하지만 와인에 대해 잘 알지 못하는 상태로 와인을 선물한다는 것은 그 과정을 어렵게 만듭니다.\r\n\r\nVi’near은 와인을 통해 특별한 날, 마음을 쉽게 전달할 수 있도록 도와주는 공간입니다.\r\n선물의 리본 끈을 묶듯이 선물을 통해 이어지는 모든 과정을 Vi’near이 함께합니다.\r\n\r\n와인을 선물하는 과정들이 모여 선물을 위한 특별한 경험이 되길 바라며.\r\nHope to become by near at heart, Vi’near',
      instagram: ['min_zzae', 'k.__.1__', 'ssun_1052_w'],
      image: [
        'https://imgur.com/DfJIBiw.jpg',
        'https://imgur.com/86Pas9b.jpg',
        'https://imgur.com/V1jqM7w.jpg',
        'https://imgur.com/iNF6nvs.jpg',
        'https://imgur.com/b3K9HJq.jpg',
        'https://imgur.com/5kYJv4r.jpg',
        'https://imgur.com/Azsrfob.jpg',
        'https://imgur.com/8lTGlfb.jpg',
        'https://imgur.com/RjfzKga.jpg',
        'https://imgur.com/rS8ZhMx.jpg',
      ],
      video: [],
      link: ['https://www.behance.net/gallery/192897763/Vinear'],
    },
    {
      thumbnail: 'https://imgur.com/hv3D1jj.jpg',
      title: '쏙, 싹, 쓱',
      author: '김소은, 이영서, 이한나',
      text: '고령층 등 디지털 약자들을 위한 스마트 기기 안내 키트 쏙입니다.\r\n스마트폰 가이드북 ’쏙 넣어서 시작하기’ 종류별 2권 (기초, 심화), 용어 정리 카드, 기타 어플 가이드북 ’쓱 앱 켜서 활용하기’, 학습지 ’싹 넘겨서 풀어보기’, 키오스크 가이드 어플 ’쏙 들어가서 주문하기’로 구성되어 있습니다.\r\n안내를 천천히 따라오다 보면 전자기기에 대한 두려움을 없앨 수 있을 거예요!',
      instagram: ['note_of_a', 'yo_eo106', ' __sucreblanc'],
      image: [
        'https://imgur.com/xfSUFRE.jpg',
        'https://imgur.com/xJalTj1.jpg',
        'https://imgur.com/G5tb8J7.jpg',
        'https://imgur.com/s5cAg4p.jpg',
        'https://imgur.com/Mf6Grpa.jpg',
        'https://imgur.com/pELiSX2.jpg',
        'https://imgur.com/whdOvr2.jpg',
        'https://imgur.com/SMdSXYP.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/ro6HYKc.jpg',
      title: 'PITA',
      author: '김채현, 박서연, 박세은, 정세진',
      text: '“혼자 하기는 어려운 운동.. 트레이너와 함께라면 해낼 수 있지 않을까?”\r\n누군가가 나의 도전을 지지하고 도와준다는 것은 우리에게 큰 동기부여가 되어줍니다.\r\n\r\n피타(PITA)는 이러한 트레이너와 수강생 사이의 지지와 도움이 서로에게 더욱 핏하게 이루어지도록 돕습니다.\r\n나에게 맞지 않는 번거롭고 불편한 연락 없이 PT의 긍정적인 동기부여만 지속하면서 PT할 시간, 피티 타임!',
      instagram: ['tol1_z', 'yeoneeseo', 'jjapagethi', 'five_ono_four'],
      image: [
        'https://imgur.com/HPpCxbk.jpg',
        'https://imgur.com/W6gJuUV.jpg',
        'https://imgur.com/qj8LZx6.jpg',
        'https://imgur.com/OXFRPhd.jpg',
        'https://imgur.com/UT5jlPh.jpg',
        'https://imgur.com/gEvc4WB.jpg',
        'https://imgur.com/DNxRa7e.jpg',
        'https://imgur.com/aKmRhXA.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/eg5AXb9.jpg',
      title: 'MODA!',
      author: '김서현, 박하경, 손서우, 이송희',
      text: '이곳저곳에 흩어져 있는 학교 관련 정보들, 찾아보기 불편하지 않으셨나요? 이제 한곳에서 모아보세요!\r\n\r\nMODA!(모다)는 대학생을 위한 학교 정보 오픈 사전 서비스로, 교내 시설과 제도에 대한 기본적인 정보부터 꿀팁까지 학생들이 직접 정보를 등록하고 수정할 수 있습니다.\r\n모다를 통해 우리 학교의 모든 것을 담은 사전을 함께 만들어 나가 보아요!',
      instagram: ['shmono', 'phk__15', 'thstjdn_sw', 'isonghyi32'],
      image: [
        'https://imgur.com/blmkC7d.jpg',
        'https://imgur.com/QAgvVPU.jpg',
        'https://imgur.com/85XBUWY.jpg',
        'https://imgur.com/EPfvw1K.jpg',
        'https://imgur.com/OjIqQZV.jpg',
        'https://imgur.com/B910AVG.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/v7C1EBl.jpg',
      title: 'FRUBE',
      author: '권수연, 박소현, 이명건, 조진주',
      text: 'FRUBE는 건강한 일상을 부담스럽지 않게 가꾸어 가고 싶은 사람들을 위한 동결건조 간식 브랜드입니다.\r\n미각, 촉각, 식감 그리고 건강까지 챙기고 싶은 사람들의 일상을 가벼운 첫 입으로 채워줄 큐브를 경험해 보세요.\r\n\r\n보다 감각적이고, 보다 건강한 당신의 일상을 위해.\r\n\r\nFor you, by earth. FRUBE',
      instagram: ['suu.yeo_n', 'outruleu', 'cyapstaye', '_manxin_doo'],
      image: [
        'https://imgur.com/DPfMoty.jpg',
        'https://imgur.com/x6gDxl7.jpg',
        'https://imgur.com/CbDFcX8.jpg',
        'https://imgur.com/aOyZWwv.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/Mmp38Sf.jpg',
      title: '차곡',
      author: '김서현, 윤유빈, 최영재',
      text: '차곡차곡 정리되는 주차장\r\n차곡차곡 만들어가는 주차 여정\r\n차곡은 보다 효율적인 공간 활용을 통해 편리한 주차 환경을 만드는 아파트 스마트 주차장입니다. 나의 일상을 함께하는 공간, 주차장에서 차곡과 함께 더 나은 일상으로 첫걸음을 내딛어볼까요?',
      instagram: ['mlikcreambread', '_uiqnh'],
      image: [
        'https://imgur.com/li4qNeZ.jpg',
        'https://imgur.com/93hAE9w.jpg',
        'https://imgur.com/3t9ulHC.jpg',
        'https://imgur.com/4oM1iSc.jpg',
        'https://imgur.com/LNW69Zt.jpg',
        'https://imgur.com/W1T1PLj.jpg',
        'https://imgur.com/osxQkml.jpg',
        'https://imgur.com/OyPFo4o.jpg',
        'https://imgur.com/f6bmoFY.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/IqKcRFL.jpg',
      title: 'TOMAK',
      author: '윤서윤, 진나경, 양찬규',
      text: '오? 이거 맛있겠다 나도 만들어 보고싶어!\r\n집에 재료가 없어 포기해버리는 레시피, 이제는 TOMAK에서 숏폼으로 마음에 드는 레시피를 발견하고 더 쉽고 빠르게 요리를 진행해봐요\r\n오늘의 요리는?\r\nToday’s dish to make',
      instagram: ['seoyunss', 'na568._.kyung'],
      image: [
        'https://imgur.com/HGrYPms.jpg',
        'https://imgur.com/6AvdgwU.jpg',
        'https://imgur.com/fYdiX3J.jpg',
        'https://imgur.com/8gNtU0n.jpg',
        'https://imgur.com/9zfhUuy.jpg',
        'https://imgur.com/YvJzPFp.jpg',
        'https://imgur.com/aWEE0AG.jpg',
        'https://imgur.com/zMnwGHe.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/J1db4Mc.jpg',
      title: 'to.two',
      author: '구윤지',
      text: '사랑은 책을 타고\r\n투투는 연인이 작성한 편지를 도서와 함께 배송받는 서비스입니다. 사랑하는 사람과 투투에서 독서 기록을 작성하고 이야기를 나누세요.',
      instagram: ['9yun_ji', 'to.two_love'],
      image: [
        'https://imgur.com/LofY1vO.jpg',
        'https://imgur.com/b4n1crw.jpg',
        'https://imgur.com/B1CEQeT.jpg',
        'https://imgur.com/fwoETkt.jpg',
        'https://imgur.com/Y6CcVl7.jpg',
        'https://imgur.com/M5NALT1.jpg',
      ],
      video: ['https://player.vimeo.com/video/923634735?h=bf1060f3c1'],
      link: [],
    },
  ],
  [
    {
      thumbnail: 'https://imgur.com/4IUwXIb.jpg',
      author: '구재혁',
      title: 'matter·energy',
      text: '아인슈타인은 그의 논문 《물체의 관성은 그 에너지양에 따라 달라지는가?》에서 특수상대성이론을 통해 질량과 에너지의 동등성을 보였다. 물질과 에너지는 결국 같은 본질일 뿐, 서로가 서로로 변화할 수 있다는 것이다.',
      instagram: ['rhovsquare'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/hangulggol_koojaehyeok_1.gif',
        'https://imgur.com/4L1j3VN.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/wErHBBw.jpg',
      author: '권순형',
      title: '躊躇躊躇',
      text: '“다음은 무슨 글자입니까?” 축을 옮길수록 첫 글자 주변에 획들이 생겨나면서 또 다른 복잡한 글자로 변모한다. 몇 획째에서 마지막 글자를 맞힐 수 있을지 테스트해 보자. 기본 글자 여럿이 모여 완전히 다른 의미를 만들어내는 한자의 특성을 가변 글꼴로 표현했다.',
      instagram: ['soonizer_'],
      image: ['https://imgur.com/llWnbav.gif', 'https://imgur.com/fneGNfj.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/7Byw52f.jpg',
      author: '김가온',
      title: '흑백존재감',
      text: '흑과 백으로 구분되는 공간. 공간과 공간이 맞닿는 곳에서 글자는 그려진다. 끊임없이 반전되는 공간의 존재감과 그에 따라 변화하는 글자의 인상을 표현한 레터링이다.',
      instagram: ['on.and.uo'],
      image: ['https://imgur.com/qzl86X0.gif', 'https://imgur.com/6dPYktZ.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/ec00g9c.jpg',
      author: '김경빈',
      title: '연실을 먹는 자들의 나라',
      text: '《오디세이아》의 〈연실을 먹는 사람들의 나라〉에서 연실은 고향으로 돌아가는 길을 막는 망각의 열매지만, 현실에서는 때때로 망각이 필요하다. 기꺼이 그 열매를 먹어 기억을 놓아주는 모습을 물에 흘려보내는 글자로 표현했다.',
      instagram: ['7.706112', '6112_graphic'],
      image: ['https://imgur.com/BNfWtM4.gif', 'https://imgur.com/9I2GKTS.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/3omJBTy.jpg',
      author: '김주현',
      title: '믿음 소망 사랑',
      text: '세상에서 가장 POP한 믿음 소망 사랑. 가장 강렬하고 팝한 조형성을 기본 단어로 이루어진 구절과, 두 마스터의 대비감을 통해 강조하여 드러냈다.',
      instagram: ['3_jhn_3', 'jh_nnn___'],
      image: ['https://imgur.com/ow7B42K.gif', 'https://imgur.com/ugThKE9.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/RKw9ue2.jpg',
      author: '김태은',
      title: 'SMILE',
      text: '웃음. 그 누구도 알 수 없는 마음속에 숨겨진 진짜 의미는 무엇일까? 주로 행복을 닮지만 때로 조용하고도 날카로운 무기를 닮는 것. 겉과 속이 다른, 표면과 이면이 다른 웃음을 표현했다.',
      instagram: ['taennnn.1', 'and.taen'],
      image: ['https://imgur.com/qmSxpMj.gif', 'https://imgur.com/WsHtqry.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/EI8xfWo.jpg',
      author: '노유진',
      title: '보글보글',
      text: '신나는 비눗방울 놀이! 포근한 봄날 나들이 필수품 보글보글 배리어블 폰트! ※ 주의사항: 세게 불면 터질 수 있습니다. 퐁! 차가운 비눗물에 후후 숨을 불어넣으면 보글보글 부풀어 방울이 된다. 부푼 비눗방울을 건드려 퐁퐁퐁퐁 터트려보자.',
      instagram: ['yes_yu_d_d', 'yesyudd'],
      image: ['https://imgur.com/fRuzfuX.gif', 'https://imgur.com/oosxIwt.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/i9bMc1B.jpg',
      author: '박시은',
      title: '​present·プレゼント',
      text: 'Present가 담긴 상자가 있다. 리본으로 プレゼント 포장된다. 새로운 시작을 맞이하는 당신에게 주어진 선물이다. 축하합니다!',
      instagram: ['parksieuni'],
      image: ['https://imgur.com/eKc9Bo8.gif', 'https://imgur.com/IayzQY7.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/FCOwJnp.jpg',
      author: '박정빈',
      title: 'Evolution',
      text: '글자는 자신의 형태를 유연하게 변화시켜 주어진 환경과 매체에 적응하고, 살아남아, 번영한다. 이는 생명체의 진화(Evolution) 과정과 닮았으며 가변 글꼴이라는 매체를 통해 진화하는 글자의 모습을 표현했다.',
      instagram: ['jbprc'],
      image: [
        'https://hivcdsiso2024.s3.ap-northeast-2.amazonaws.com/hangulggol_parkjungbin_1.gif',
        'https://imgur.com/EMf7VHf.jpg',
      ],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/EWboMkr.jpg',
      author: '신채원',
      title: '긴장 안 했는데요?',
      text: '“저 정말 긴장 안 했는데요...” 어떻게든 당당한 척 해보려 했지만, 야속하게도 자꾸만 갈라지는 글자. 엄청난 긴장감은 글로 써도 숨길 수가 없었다. 맞아요, 사실 긴장했어요!',
      instagram: ['wontheonethewonder', 'wxtoxtw'],
      image: ['https://imgur.com/axEu2bN.gif', 'https://imgur.com/eVAzkBJ.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/PsIKKQm.jpg',
      author: '이주아',
      title: '어떻게 사랑이 변하니',
      text: '영화 《봄날은 간다》의 대사 ‘어떻게 사랑이 변하니’를 레터링 했다. 사랑이 식고 변하는 과정을 글자에 담았다. 서로 부드럽게 이어져 있던 곡선이 뾰족한 끝을 가진 직선으로 바뀌며 멀어진다.',
      instagram: ['aaah_process'],
      image: ['https://imgur.com/yX0Qyxo.gif', 'https://imgur.com/FwbZCuc.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/ekh35Kn.jpg',
      author: '전재곤',
      title: 'TENSION',
      text: '‘TENSION’. 글자 형상의 프레임과 그것을 기반으로 팽팽하게 연결된 선들로 조직된 레터링. 선은 가변 값의 조절에 따라 당겨지며 긴장감과 에너지를 발생시킨다.',
      instagram: ['kamesu_shi'],
      image: ['https://imgur.com/1NH4QV7.gif', 'https://imgur.com/zOWgDAc.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/nVvyvCh.jpg',
      author: '정우성',
      title: 'Ready',
      text: '출발선에 선 사람들은 준비 신호(Ready) 소리와 동시에, 몸을 움츠리는 준비 동작을 취하며 경직된다. 근육이 오그라드는 것처럼, 출발 직전에 느껴지는 긴장감을 획의 방향에 따라 수축하며 변화하는 글자를 통해 표현했다.',
      instagram: ['w00_sung', 'w00_rk'],
      image: ['https://imgur.com/V77dWqo.gif', 'https://imgur.com/lkBA0FC.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/GBDZgxl.jpg',
      author: '조영재',
      title: '소리없는아우성',
      text: '단어는 언어와 시각의 면에서 여러 의미를 가진다. 이는 연결되어 있음에도 때로는 의미들의 관계 속에서 충돌한다. 변화하는 형태를 통해 의미들이 서로 만나고 충돌하는 과정을 담았다.',
      instagram: ['choyoungjaeis', 'ch00jaeis'],
      image: ['https://imgur.com/OJZb16k.gif', 'https://imgur.com/vO0MwpL.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/uZH5QnR.jpg',
      author: '진서영',
      title: '반짝 빤닥 펠롱',
      text: '우리는 무엇을 ‘반짝’거린다고 느낄까? 중앙으로 모이는 형태, 나타났다가 사라지는 존재, 커졌다가 작아지는 크기. 세 가지 특성을 ‘반짝’, ‘빤닥’, ‘펠롱’ 세 가지 단어에 담았다. *빤닥: ‘반짝’의 전라남도 방언, 펠롱: ‘반짝’의 제주도 방언',
      instagram: ['the.fishgirls'],
      image: ['https://imgur.com/QpMelNk.gif', 'https://imgur.com/jTdJC0b.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/bYfn9vq.jpg',
      author: '한수영',
      title: '움츠린 파도·숨쉬는 파도',
      text: '파도는 바다의 숨소리이다. 긴장된 호흡을 내뱉으며 움츠러들다가 마침내 긴 숨을 내쉰다. 바다의 숨소리를 글자의 호흡으로 느껴보자.',
      instagram: ['zeroswim_'],
      image: ['https://imgur.com/H11AeDg.gif', 'https://imgur.com/8Terdhl.jpg'],
      video: [],
      link: [],
    },
    {
      thumbnail: 'https://imgur.com/LgWxM40.jpg',
      author: '한시연',
      title: '나이트메어',
      text: '한밤중 우리를 삼킨 건 단지 악몽일 뿐. 해가 뜨면 모두 사라질 걸 알지만, 두려움은 여전하다. 평온한 낮과 악몽이 찾아오는 밤을 대조해 글자로 표현했다.',
      instagram: ['c2yeon', 'mauvemimosa'],
      image: ['https://imgur.com/RGppPqf.gif', 'https://imgur.com/VM2OH0Z.jpg'],
      video: [],
      link: [],
    },
  ],

  [
    //힙스
    {
      title: '허-공간 개입',
      author: '김경빈',
      text: '주거지의 탄생과 해체 그리고 순환의 발생은 필연적이다. 소멸과 보존이라는 언어 사이에 위치한 공간을 탐색한다. 균형을 유지하던 공간이 소멸에 가까워질 때 주거지를 구성하던 잔해들이 지면으로 가라앉는다.',
      instagram: ['kyungbinkiim'],
      thumbnail: 'https://imgur.com/UoSA0Gm.jpg',
      image: ['https://imgur.com/AssDvTH.jpg'],
      video: [],
      link: [],
    },
    {
      title: '조화 (Artificial flowers)',
      author: '김동혜',
      text: '나이브한 태도에 대한 경계, 동시에 이와 충돌하는 나이브하고 싶은 욕구의 모순. 여기 그 욕망이 심어져 슬며시 가지를 뻗고 있다.',
      instagram: ['vvexyzet'],
      thumbnail: 'https://imgur.com/sCyw0Wq.jpg',
      image: ['https://imgur.com/RUKv6Cb.jpg', 'https://imgur.com/PQQywQe.jpg', 'https://imgur.com/roLZwc1.jpg'],
      video: [],
      link: [],
    },
    {
      title: 'Heritage',
      author: '김예린',
      text: '덩어리를 가르면 복잡한 것들이 모습을 드러낸다. 과실을 가르니 상흔이 보인다.',
      instagram: ['linlinxlin'],
      thumbnail: 'https://imgur.com/r05Mdh5.jpg',
      image: ['https://imgur.com/rYJX9jh.jpg'],
      video: [],
      link: [],
    },
    {
      title: '칠',
      author: '성경찬',
      text: '여전히 담고 싶은 것은 색인 것 같다. 다만 한 가지 달라진 것이 있다면, 색을 담는 과정에서 나의 개입이 생기는 것. 빛이 거친 표면에 감기면서 새로운 색을 칠한다. 의도하였지만 우연적인 현상이 오묘하고도 아름다운 색을 만들어 냈다.',
      instagram: ['bibl_uee'],
      thumbnail: 'https://imgur.com/EMnQizM.jpg',
      image: [
        'https://imgur.com/ZPR87Ug.jpg',
        'https://imgur.com/N3YgEn3.jpg',
        'https://imgur.com/nLhP7HO.jpg',
        'https://imgur.com/1rAphCl.jpg',
      ],
      video: [],
      link: [],
    },
    {
      title: '회귀',
      author: '이린',
      text: '결국 원래대로 돌아오는 것 같은 때가 있다. 미래로 나아가는 것이 과거로의 회귀처럼 느껴진다. 그러나 현재를 거친 후 회귀하는 나는 과거와 달라져있다. 처음과는 같을 수 없는 것이 있다.',
      instagram: ['llnnnyl'],
      thumbnail: 'https://imgur.com/SCVkV6a.jpg',
      image: [
        'https://imgur.com/4A2JU8L.jpg',
        'https://imgur.com/dDewShD.jpg',
        'https://imgur.com/0FqYS6G.jpg',
        'https://imgur.com/W06dXbG.jpg',
        'https://imgur.com/QvR52St.jpg',
        'https://imgur.com/8DzJqPy.jpg',
        'https://imgur.com/mJtpPp5.jpg',
        'https://imgur.com/3P0xcVh.jpg',
        'https://imgur.com/ggo0QRI.jpg',
      ],
      video: [],
      link: [],
    },
    {
      title: '그 속에 들어 살기 위한',
      author: '이지현',
      text: '아끼고 그리워하기에, 현재의 속에 들기 위하여, 끊임없이 타협하며 조금씩 모양새를 바꿔간다.',
      instagram: ['easy_xuan'],
      thumbnail: 'https://imgur.com/FpGQRZb.jpg',
      image: [
        'https://imgur.com/NBrPAv4.jpg',
        'https://imgur.com/FwuvUjM.jpg',
        'https://imgur.com/6gUHXqX.jpg',
        'https://imgur.com/w1eDgvB.jpg',
      ],
      video: [],
      link: [],
    },
    {
      title: 'remains',
      author: '이지희',
      text: '나는 숨 쉴 구멍 하나 없는 돌을 압축시킨다. 돌을 진공 상태에 가두는 행위에 이어 있는 힘껏 석고 붕대로 압박하기를 반복해왔다. 해방될 수 없다는 것을 전제로 반복적인 쌓는 행위가 남긴 잔재 (부스러기들)를 추적하며 직면한다.',
      instagram: ['zzzzheee_'],
      thumbnail: 'https://imgur.com/Hk878iV.jpg',
      image: ['https://imgur.com/9Rbjsdx.jpg', 'https://imgur.com/WvakzMA.jpg', 'https://imgur.com/03XMNOU.jpg'],
      video: [],
      link: [],
    },
    {
      title: "Hayne's on a Plane",
      author: '이해인',
      text: '방랑과 여행을 통해 내 고향을 찾는 과정을 표현한다. 그 과정은 끊임없는 탐구와 발견의 여정으로, 나 자신과 세계 간의 연결고리를 탐색하는 순례이다. 작품을 통해 나는 시공간을 넘나들며 과거의 경험을 모방하고, 이 기억들을 되살려 내가 속하는 곳을 발견하고자 한다.',
      instagram: ['haynsum'],
      thumbnail: 'https://imgur.com/tUIACXS.jpg',
      image: ['https://imgur.com/IXaysDZ.jpg', 'https://imgur.com/JzMQiSL.jpg', 'https://imgur.com/a4uAcFg.jpg'],
      video: [],
      link: [],
    },
    {
      title: '무제',
      author: '정은우',
      text: '완전한 무정의 대상 앞에 선 유정적 존재는 일종의 자괴감을 느낀다. 불완전한 존재의 불안은 이를 해소할 방법을 모색한다. 이상적 존재와 온전히 마주하려는 연습의 과정을 담는다.',
      instagram: ['eunuyed'],
      thumbnail: 'https://imgur.com/OeDdFJD.jpg',
      image: ['https://imgur.com/WBVIUVy.jpg', 'https://imgur.com/J0PRap4.jpg', 'https://imgur.com/aOML85b.jpg'],
      video: [],
      link: [],
    },
    {
      title: '10',
      author: '한연수',
      text: '까맣게 타 버린 장판, 오물이 묻은 이불, 그리고 먼지 쌓인 식탁 위의 썩은 단감, 그가 누워 있던 좁은 방과 그 안의 사물들에 약간의 조작을 가한다. 축적된 시간에 선과 면, 부피를 부여함으로써 쇠락된 기억의 잔재를 읽는다.',
      instagram: ['anveosu'],
      thumbnail: 'https://imgur.com/ALfxzFZ.jpg',
      image: ['https://imgur.com/PjJfW1N.jpg', 'https://imgur.com/UcWhbYZ.jpg'],
      video: [],
      link: [],
    },
    {
      title: '핫 픽셀',
      author: '힙스 시소 참여인원 전체 작업',
      instagram: ['hips_official'],
      text: '이 책, [ 핫 픽셀 ] 은 2024년도 홍익대학교 시각디자인과 소모임 축제주간 중, HIPS (사진예술소모임) 의 [워크스, 플러스, 페이스] 전의 연계 작업이다.\r\n[ 핫 픽셀 ]은 HIPS 부원들이 쌓아 만들어오던 이미지들 중 미처 전시되지 못한 B컷들, 일상의 순간, ‘작업’ 이라는 명칭을 붙이기에는 망설여지던 사진들을 한데 모아 만들어진 더미북이다. ‘불량 화소’ 로 분류되어 핫 픽셀의 형태로 부원들 각자의 저장 공간 속에 잠들어있던 데이터 이미지들을 깨워, 물성을 가진 인쇄물의 형식으로 이들을 선보이고자 한다.',
      thumbnail: 'https://imgur.com/uxgZqmM.jpg',
      image: [
        'https://imgur.com/SNu3CpP.jpg',
        'https://imgur.com/dFR1FL8.jpg',
        'https://imgur.com/SRh4jte.jpg',
        'https://imgur.com/lINccib.jpg',
        'https://imgur.com/sWIbPf8.jpg',
        'https://imgur.com/tFH5NFM.jpg',
        'https://imgur.com/dUl7Vug.jpg',
        'https://imgur.com/wHrQ7LW.jpg',
        'https://imgur.com/KGadVo6.jpg',
        'https://imgur.com/jeZe0nf.jpg',
      ],
      video: [],
      link: [],
    },
  ],
];
