export const DATA_SETS = [
  [
    // 그린비
    {
      thumbnail: 'https://i.pinimg.com/564x/f9/b2/42/f9b24249e31d651a820de05037281d3a.jpg',
      title: 'Title TextField',
      author: '강민서',
      instagram: 'm._.__s',
      text: '국민경제의 발전을 위한 중요정책의 수립에 관하여 대통령의 자문에 응하기 위하여 국민경제자문회의를 둘 수 있다. 대한민국은 통일을 지향하며, 자유민주적 기본질서에 입각한 평화적 통일 정책을 수립하고 이를 추진한다. 지방자치단체는 주민의 복리에 관한 사무를 처리하고 재산을 관리하며, 법령의 범위안에서 자치에 관한 규정을 제정할 수 있다. 재산권의 행사는 공공복리에 적합하도록 하여야 한다. 국회는 법률에 저촉되지 아니하는 범위안에서 의사와 내부규율에 관한 규칙을 제정할 수 있다. 국회의 정기회는 법률이 정하는 바에 의하여 매년 1회 집회되며, 국회의 임시회는 대통령 또는 국회재적의원 4분의 1 이상의 요구에 의하여 집회된다.',
      image: [
        'https://imgur.com/iPhwMk2.gif',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqFK8Yjbmd3MRLSCQr8wL9KwEuP7UG-mMpOw&s',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqFK8Yjbmd3MRLSCQr8wL9KwEuP7UG-mMpOw&s',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqFK8Yjbmd3MRLSCQr8wL9KwEuP7UG-mMpOw&s',
      ],
    },
    {
      thumbnail: 'https://i.pinimg.com/736x/1f/5c/96/1f5c966c2cff5a530d2e8238576a1e7b.jpg',
      title: 'Title Text',
      author: '강민서',
      text: '글자설명',
      instagram: '',
      image: ['imageurl2', 'url'],
    },
    {
      thumbnail: 'https://i.pinimg.com/736x/1f/5c/96/1f5c966c2cff5a530d2e8238576a1e7b.jpg',
      title: 'Title Text',
      author: '강민서',
      text: '글자설명',
      instagram: '',
      image: ['imageurl1', 'imageurl2', 'url'],
    },
    {
      thumbnail: 'https://i.pinimg.com/736x/1f/5c/96/1f5c966c2cff5a530d2e8238576a1e7b.jpg',
      title: 'Title Text',
      author: '강민서',
      text: '글자설명',
      instagram: '',
      image: ['imageurl1', 'imageurl2', 'url'],
    },
    {
      thumbnail: 'https://i.pinimg.com/736x/1f/5c/96/1f5c966c2cff5a530d2e8238576a1e7b.jpg',
      title: 'Title Text',
      author: '강민서',
      text: '글자설명',
      instagram: '',
      image: ['imageurl1', 'imageurl2', 'url'],
    },
    {
      thumbnail: 'https://i.pinimg.com/736x/1f/5c/96/1f5c966c2cff5a530d2e8238576a1e7b.jpg',
      title: 'Title Text',
      author: '강민서',
      text: '글자설명',
      instagram: '',
      image: ['imageurl1', 'imageurl2', 'url'],
    },
    {
      thumbnail: 'https://i.pinimg.com/736x/1f/5c/96/1f5c966c2cff5a530d2e8238576a1e7b.jpg',
      title: 'Title Text',
      author: '강민서',
      text: '글자설명',
      instagram: '',
      image: ['imageurl1', 'imageurl2', 'url'],
    },
    {
      thumbnail: 'https://i.pinimg.com/736x/1f/5c/96/1f5c966c2cff5a530d2e8238576a1e7b.jpg',
      title: 'Title Text',
      author: '강민서',
      text: '글자설명',
      instagram: '',
      image: ['imageurl1', 'imageurl2', 'url'],
    },
  ],
  [
    // 드로마픽
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],
  [
    // 아이레이
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: '아이레이',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],
  [
    // 야즈
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: '야즈',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],
  [
    // 애드레날린
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],
  [
    // 프로토
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],
  [
    // 하이픈
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],
  [
    // 한글꼴연구회
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],

  [
    // 힙스
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: '',
      image: ['imageurl1', 'imageurl2'],
    },
  ],
];
