export const DATA_SETS = [
  [
    // 그린비
    {
      thumbnail: 'https://imgur.com/kAX1XQW.jpg',
      title: 'New-Etiquette Project',
      author: '강소정',
      instagram: ['szunok'],
      text: '이른바 뉴-에티켓 프로젝트는 범람 시대 속 클릭 한 번, 좋아요 한 번으로 소비되고 버려지는 인스턴트 관계성들을 극복하기 위해 탄생되었다. 이것은 우리가 이미 실행하고 있는 암묵적인 배려들을 ‘에티켓’의 범주 안에서 새롭게 재분류한 것으로, 지극히 일상적이면서도 타인과의 직접적인 접촉을 요한다. 뉴-에티켓을 통해 관계를 깊게, 또 느리게 음미해보자.',
      image: [
        'https://imgur.com/mAJjO97.jpg',
        'https://imgur.com/Es9MJ3T.jpg',
        'https://imgur.com/uVLHkrU.jpg',
        'https://imgur.com/f59biJ1.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/1UfMZBp.jpg',
      title: 'All-in-One Impromptu',
      author: '김규빈',
      text: 'Epson L4150과 함께 연주한다. 좀처럼 마음대로 움직여 주지 않는 나의 복합기는 같은 데이터를 매번 다르게 산출해 낸다. 결과는 예상할 수 없다. 지면 여백을 무시하기도 하고, 검은색 글씨를 하얀색으로 출력하기도 한다. 디지털로 이루어진 동일한 데이터들은 나의 복합기를 거치며 각기 다른 형태로 변화한다.',
      instagram: ['streetpessimist'],
      image: [
        'https://imgur.com/58V3j9Q.jpg',
        'https://imgur.com/4cKNE6o.jpg',
        'https://imgur.com/XS71vam.jpg',
        'https://imgur.com/MdZnTqQ.jpg',
        'https://imgur.com/HiBj7tQ.jpg',
        'https://imgur.com/4lpioQV.jpg',
        'https://imgur.com/zcIq0ap.jpg',
        'https://imgur.com/4bt9p8n.jpg',
        'https://imgur.com/tVLUX1V.jpg',
        'https://imgur.com/E3vqdSa.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/zPQnXLd.jpg',
      title: '지면에 지면을 지면',
      author: '김린 & 양해든',
      text: '지당히 디딘 채 지나쳐간 수많은 지면(地面)은 한 장의 지면(紙面) 위에 지어졌고, 우리가 관심할 때 비로소 저마다의 정체성을 향유한다. ‘지면에 지면을 지면’은 땅의 거죽을 종이의 겉면으로 옮기는 과정과 그에 따른 가시적 결과물을 포괄한다.',
      instagram: ['_haedeun', 'lyynkm'],
      image: ['https://imgur.com/GpzDNro.jpg', 'https://imgur.com/1VgQQZd.jpg'],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/6uVvAlR.jpg',
      title: 'UWW(Universe Wide Web)',
      author: '김민주',
      text: 'UWW(Universe Wide Web)는 기존의 지구 내에서만 사용되던 WWW을 바탕으로 제작된 인터넷서비스입니다. UWW를 통해 외계행성을 탐험하고 시공간을 초월하여 메시지를 전송해 보세요. 무한한 우주를 향해 한 걸음 다가서세요.',
      instagram: ['juya_0905'],
      image: [
        'https://imgur.com/Mc0V6H4.jpg',
        'https://imgur.com/kNDQjx2.jpg',
        'https://imgur.com/69U6KlP.jpg',

        'https://imgur.com/sko6b2Q.jpg',
        'https://imgur.com/9w9ECKh.jpg',

        'https://imgur.com/rbs5WZk.jpg',
        'https://imgur.com/GktexCu.jpg',
        'https://imgur.com/HtlsbaD.jpg',

        'https://imgur.com/eh3CehH.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/VupPff6.jpg',
      title: 'Desperate Dance to Doom',
      author: '김수아',
      text: '1999년 12월 31일, 모든 컴퓨터가 멈추고 세계 종말의 카운트다운이 시작된다. 테크노 클럽 Y2K는 멸망을 춤으로 잊어버리려는 필사적 댄스 파티를 벌인다. 죽음의 순간이 두려우십니까? 피할 수 없다면 즐겨라! ',
      instagram: ['soo.a.khy.m'],
      image: [
        'https://imgur.com/XBlrWKf.jpg',
        'https://imgur.com/u7XhW9S.jpg',
        'https://imgur.com/23BJivz.jpg',
        'https://imgur.com/axTdSf3.jpg',
        'https://imgur.com/RV9m2no.jpg',
        'https://imgur.com/atYBY4R.jpg',
      ],
      video: ['https://www.youtube.com/embed/uId97Qz3Jfs?si=pnf8BM2B-3rlvf1B'],
    },
    {
      thumbnail: 'https://imgur.com/bLzXKjL.jpg',
      title: 'New Value',
      author: '김유진',
      text: '마르셀 뒤샹이 레디메이드를 고안하게 된 이유는 무엇이었을까요? 아마 그는 지금의 우리와 같은 기분이었을 겁니다. 매일 새로운 브랜드가 쏟아지고, 우리 모두는 새로운 제품 아이디어를 내는 것에 지쳤어요. 그냥 기성품에 로고만 새겨서 판매할 겁니다. 세계 최초 레디메이드 브랜드인 우리는, 말 그대로 ‘새롭고, 특별하고, 유일무이한 가치’라고 새겨서 사물의 새로운 가치를 만들어낼 거예요. 그리고 그것이 우리 브랜드의 차별점이 될 겁니다.',
      instagram: ['eiiig_giiie'],
      image: [
        'https://imgur.com/hZofSsg.jpg',
        'https://imgur.com/DKUnTSC.jpg',
        'https://imgur.com/EjbTke2.jpg',
        'https://imgur.com/8bTqdmI.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/I7eLTb5.jpg',
      title: '사유의 서재',
      author: '박수민',
      text: '생각하기에 살아가는 인간에게, 그리고 사유하는 모든 존재들을 위해. 사유의 서재 [biblĭŏthéca de cogĭtátĭo] 의 모든 것들은 방문객에게 질문합니다. ‘당신은 어떤 생각을 하고 있나요?’',
      instagram: ['me.llamo_llamo'],
      image: [
        'https://imgur.com/CnaPqUd.jpg',
        'https://imgur.com/Ix8ZVWo.jpg',
        'https://imgur.com/Taz6USK.jpg',
        'https://imgur.com/uMcenlM.jpg',
        'https://imgur.com/6BzErO5.jpg',
        'https://imgur.com/MQALMRH.jpg',
        'https://imgur.com/GJ9vKw6.jpg',
        'https://imgur.com/cGUeMbw.jpg',
        'https://imgur.com/CDOMql2.jpg',
        'https://imgur.com/ry7kiIJ.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/hC5E9JD.jpg',
      title: 'Blob sockS',
      author: '박예진',
      text: '발의 모양은 제각각이지만 양말은 각자의 발에 맞게 변합니다. ‘Blob sockS’는 이런 양말의 특징을 점균류라는 단세포 생명체와 연결시킨 양말 브랜드입니다. \r\n점균류는 괴생명체같이 보이지만 발이 없어도 이곳저곳 옮겨 다닐 수 있고, 소화기관이 없는데도 여러 다른 생물들을 잡아먹을 수 있습니다. 심지어는 뇌나 신경계가 없는데도 기억을 하고 학습을 합니다.점균류가 가지고 있는 유일무이한 특징을 담은 양말을 선보입니다!',
      instagram: ['yeworksdesign'],
      image: [
        'https://i.imgur.com/edkd9Oj.jpg',
        'https://imgur.com/GqGFvqU.jpg',
        'https://imgur.com/QlTFD7l.jpg',
        'https://imgur.com/6qFhLOU.jpg',
        'https://imgur.com/efbxTSG.jpg',
        'https://imgur.com/1EW3w5A.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/caHNdjr.jpg',
      title: 'fil(+)aylist',
      author: '어영은',
      text: '범람하는 자기표현의 시대 속에서 우리는 종종 길을 잃기도 합니다.\r\n그런 당신에게 길잡이가 되어줄 〈 fil(+)aylist 〉\r\n당신에게 어울리는 음악(playlist), 그리고 인스타그램 필터(filter)를 추천해 드립니다!',
      instagram: ['_0urloveisgreat'],
      image: [
        'https://imgur.com/caHNdjr.jpg',
        'https://imgur.com/UsawQEy.jpg',
        'https://imgur.com/JEpUMqY.jpg',
        'https://imgur.com/8N84NcY.jpg',
        'https://imgur.com/WYlAuIe.jpg',
        'https://imgur.com/zDHe8Pt.jpg',
        'https://imgur.com/5vPjMFA.jpg',
        'https://imgur.com/DWq15ab.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/3KLoZe9.jpg',
      title: 'SPYSPECT',
      author: '오윤서 & 이연우',
      text: '39xx년, 외계에서 온 우주인 woo와 oh가 우연한 사고로 지구에 착륙했습니다. 새로운 환경에 적응하며 존재를 숨기는 동안, 지구인들의 표면에 감춰진 정체성을 이해하기 위한 특수 안경을 제작합니다. 그 특별한 안경은 우리에게 새로운 가능성을 보여주었습니다. 이제 우리, woo와 oh는 지구인 탐색 사업을 시작합니다.',
      instagram: ['y0_13s', '_u_ye0n'],
      image: [
        'https://imgur.com/NEmvdeA.jpg',
        'https://imgur.com/ogoViAn.jpg',
        'https://imgur.com/Qmt5Cqi.jpg',
        'https://imgur.com/7nB2yUb.jpg',
        'https://imgur.com/IgIu2et.jpg',
        'https://imgur.com/EsmHhcR.jpg',
        'https://imgur.com/elSaKNj.jpg',
        'https://imgur.com/hjeI7Rh.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/JidQLJo.jpg',
      title: 'Musée des Trucs Qui m’ont Choqué',
      author: '유은지',
      text: 'Musée des Trucs Qui m’ont Choqué는 ‘나에게 충격을 준 것들에 대한 박물관’이라는 뜻이다. 인류는 일상의 큰 부분을 인터넷과 소셜 미디어에 의존하기 시작한 지 수십 년이 되어가는 동안 다방면에서 취약해졌다. 이제 그들은 왜곡된 입력, 과대 해석된 분류, 모방으로부터 나오는 출력의 과정을 통해 정보를 처리하게 되었다. 각 단계를 보여주는 세 전시실을 관람하며 망가진 정보 처리 프로세스를 몰래 들여다보자.',
      instagram: ['neunji.archive'],
      image: [
        'https://imgur.com/HqRXTht.jpg',
        'https://imgur.com/hljBtPL.jpg',
        'https://imgur.com/i6VlFkE.jpg',
        'https://imgur.com/mgpFbpq.jpg',
        'https://imgur.com/yyo2Uis.jpg',
        'https://imgur.com/3afQSm8.jpg',
        'https://imgur.com/UkTjRtF.jpg',
        'https://imgur.com/rv2YKVB.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/5ySZSh1.jpg',
      title: 'Ruminola village',
      author: '윤채원',
      text: '어서 오세요! 루미놀라 마을에 오신 것을 환영합니다. 저희 마을은 정체성의 위기라는 큰 재앙을 이겨낸 정체불명 생명체들이 모여 만들어진 마을입니다. 위기를 견뎌내고 살아남은 여러분, 루미놀라에 입주할 수 있는 특별한 기회를 놓치지 마세요!',
      instagram: ['ycwony'],
      image: [
        'https://imgur.com/P6iAdqh.jpg',
        'https://imgur.com/BXrm20Q.jpg',
        'https://imgur.com/QFAVOHi.jpg',
        'https://imgur.com/sW4Gdpz.jpg',
        'https://imgur.com/lTS4QVP.jpg',
        'https://imgur.com/mGAP7UF.jpg',
        'https://imgur.com/yxgDGCK.jpg',
        'https://imgur.com/P8xpzGM.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/704jw19.jpg',
      title: 'Look at the real self',
      author: '이연주',
      text: '작업을 시작할 때 가장 먼저 레퍼런스를 찾곤 한다. 세상에는 멋진 이미지가 이미 너무 많으니까. 세상에는 이미지가 너무 많아서 왜 이렇게 만들었을지는 고민할 시간이 없고는 하지만, 오늘만큼은 자세히 들여다보자. 그리고 그 안에 숨겨진 모습을 발견하자.',
      instagram: ['yeo.nnju'],
      image: [
        'https://imgur.com/SL7gF4R.jpg',
        'https://imgur.com/DTERql9.jpg',
        'https://imgur.com/3nRK2Sq.jpg',
        'https://imgur.com/jwmkG6W.jpg',
        'https://imgur.com/aPVb10N.jpg',
        'https://imgur.com/geNDZLQ.jpg',
        'https://imgur.com/yHREGIF.jpg',
        'https://imgur.com/s0b66ZL.jpg',
        'https://imgur.com/uqCRMO8.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/nlrbsUM.jpg',
      title: 'Infinity',
      author: '이예은',
      text: '수렴적 상향구조를 가진 팽창 우주는 그 특성이 마치 헤겔의 변증법과 유사해 보이기도 합니다. 변증법적 시선으로 우주의 무한함을 따라가다 보면, 우주는 우리를 무한한 발견과 새로운 가능성으로 이끕니다. 끝없는 시공간 속에서 우리는 또 무엇을 찾게 될까요? Infinity와 함께 새로운 여행이 시작됩니다.',
      instagram: [''],
      image: [
        'https://imgur.com/PED1JB4.jpg',
        'https://imgur.com/MV5mNei.jpg',
        'https://imgur.com/ZFq2HUL.jpg',
        'https://imgur.com/ebSzO3b.jpg',
        'https://imgur.com/3sODMqd.jpg',
        'https://imgur.com/CEDkDi7.jpg',
      ],
      video: ['https://www.youtube.com/embed/hOuLFsYohdM?si=8xDugjzTX_nXyj0o'],
    },
    {
      thumbnail: 'https://imgur.com/y5ZTh5M.jpg',
      title: 'TTfestival',
      author: '이지원',
      text: '자본주의의 시대라는 이름 아래 스스로를 판매대 위에 올리는 사람들, 깎여나가는 자신만큼 생기는 고민과 고뇌, 그리고 그를 폄하하는 세태. 우리는 그런 사람들을 위해 "쓰레기" 같은 고민을 던지는 축제를 개최했습니다. 누구든 편히 고뇌하고 앓을 수 있습니다. 이 축제가 끝나는 날에, 조금 더 서로를 이해하고 화합할 수 있길 바랍니다.',
      instagram: ['LeeJIwon'],
      image: [
        'https://imgur.com/T3BqYLw.jpg',
        'https://imgur.com/JtkYQVE.jpg',
        'https://imgur.com/ePQ4vOh.jpg',
        'https://imgur.com/1mSjyZN.jpg',
        'https://imgur.com/p3Cnh73.jpg',
        'https://imgur.com/dwOx0m8.jpg',
        'https://imgur.com/n39JRyZ.jpg',
        'https://imgur.com/wuGuPt4.jpg',
        'https://imgur.com/Bz5zR9l.jpg',
        'https://imgur.com/vCIc6Le.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/30r4G4h.jpg',
      title: 'ememi',
      author: '전지원',
      text: 'ememi(egg me my identity)는 독보적인 커스터마이징 젤리를 선사합니다. 개성이 퇴색되며 표준화된 세상에서, 독특한 정체성을 존중함과 동시에 당신만의 개성을 성장시키는 ememi와 함께 특별하고 독창적인 존재로 거듭나세요.',
      instagram: ['wonnieji__'],
      image: [
        'https://imgur.com/uGuPj3R.jpg',
        'https://imgur.com/FmJhONt.jpg',
        'https://imgur.com/8oIgEfU.jpg',
        'https://imgur.com/N648KWh.jpg',
        'https://imgur.com/bwofWEi.jpg',
      ],
      video: ['https://youtu.be/iyj9D2249xU'],
    },
    {
      thumbnail: 'https://imgur.com/ZRubcjD.jpg',
      title: 'Fever Fish',
      author: '정예원',
      text: '열병을 앓고 있는 사람들의 눈앞에서는 자유롭게 유영하는 물고기가 일렁거린다. 혼란스럽고 불확실한 청춘의 시기에 찾아온 물고기들, 내게 보이는 물고기의 종류를 알면 이 지독한 열병을 진단할 수 있지 않을까.',
      instagram: ['ywon_512'],
      image: [
        'https://imgur.com/hq4GT5p.jpg',
        'https://imgur.com/fCNV6Xj.jpg',
        'https://imgur.com/EONFZiC.jpg',
        'https://imgur.com/aLPZjOp.jpg',
        'https://imgur.com/NtmLtRw.jpg',
        'https://imgur.com/a9uzpXi.jpg',
        'https://imgur.com/0iAme14.jpg',
        'https://imgur.com/BVgepXh.jpg',
        'https://imgur.com/y7Ii2S1.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/am9yIVE.jpg',
      title: 'Permaphic 1.0',
      author: '조승완',
      text: '오래된 컴퓨터 한 구석에서 이상한 프로그램을 발견했다. 잃어버린 그래픽을 찾아 주는 Permaphic 그래픽 생성기...? Permaphic 그래픽 생성기를 통해 나의 잃어버린 그래픽을 찾아나가 보자.',
      instagram: ['sungwanizer'],
      image: [
        'https://imgur.com/qXktKXi.jpg',
        'https://imgur.com/saBKlo0.jpg',
        'https://imgur.com/HebGrVp.jpg',
        'https://imgur.com/aIgrYZk.jpg',
        'https://imgur.com/FZDMzXC.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/w8SMg6n.jpg',
      title: 'Basic Instinct (원초적 본능)',
      author: '조예린',
      text: '미디어와 자본이 인류의 사고와 행동을 결정하는 현대, 인류는 주체성을 잃어버리고 문명의 노예가 되었다. 한 연구단체는 이에 대항하기 위해 인간의 본원을 회복해 탈의존화된 신인류를 만들어내는 프로젝트 〈원초적 본능〉을 비밀리에 착수한다. 원초적 신인류는 문명에 의해 무뎌진 치아구조를 탈피하고 인간의 본질적인 형태를 갖추어나간다.',
      instagram: ['yelling_bird'],
      image: [
        'https://imgur.com/ozabtIq.jpg',
        'https://imgur.com/Duo46xh.jpg',
        'https://imgur.com/I3Y2DxM.jpg',
        'https://imgur.com/f4qe8PV.jpg',

        'https://imgur.com/vn5xI6F.jpg',
        'https://imgur.com/FVgPso2.jpg',
        'https://imgur.com/Iqk32HS.jpg',
        'https://imgur.com/5A31frh.jpg',
        'https://imgur.com/E2vafL6.jpg',
        'https://imgur.com/QlK1HsX.jpg',
      ],
      video: ['https://www.youtube.com/embed/DmTyrAGV0z0?si=m6V3dq4u8XO4rocF'],
    },
    {
      thumbnail: 'https://imgur.com/Ga4fYcb.jpg',
      title: 'plantform',
      author: '조훈규',
      text: 'Make your own plant! plantform은 당신이 선택한 식물들로만 조합된 세상에 하나뿐인 식물을 선물해 드립니다. planform의 독특한 방식을 통해 당신만의 새로운 리폼식물을 만들어보세요. 지금 바로 주문서를 작성해보세요!',
      instagram: ['hooonkyu'],
      image: [
        'https://imgur.com/noEWYoK.jpg',
        'https://imgur.com/MKQv0Sx.jpg',
        'https://imgur.com/7I5m3QV.jpg',
        'https://imgur.com/0rtTzZd.jpg',
        'https://imgur.com/zgHLLr8.jpg',
        'https://imgur.com/96vLpq0.jpg',
        'https://imgur.com/D0dI442.jpg',
        'https://imgur.com/NkfluQp.jpg',
        'https://imgur.com/zmGbibD.jpg',
        'https://imgur.com/aen3EDa.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/p553ZAb.jpg',
      title: '옅어져 사라진다',
      author: '하수민',
      text: '겨울엔 동백나무가, 봄엔 벚꽃이 아름답게 피어나 세상을 오색찬란한 빛으로 물들인다. 다채로운 색채로 자연을 가꾸어 주던 꽃잎들은 표준화된 기준에 자신을 맞추려 본래의 색을 서서히 잊어간다. 선명히 옅어져가는 꽃잎들 속에서 우리는 어떤 색의 꽃을 피워내고 싶은가.',
      instagram: ['sx.xxn_'],
      image: [
        'https://imgur.com/sYTkMnu.jpg',
        'https://imgur.com/Y7Y4lZH.jpg',
        'https://imgur.com/eKQGCxf.jpg',
        'https://imgur.com/s9hbzZ4.jpg',
        'https://imgur.com/TNcps3i.jpg',
      ],
      video: [],
    },
    {
      thumbnail: 'https://imgur.com/TWqB0VC.jpg',
      title: 'DREAM AUCTION',
      author: '현혜영',
      text: '태어날 때부터 녹화되는 꿈 테이프를 사고파는 세계. 우리는 오늘도 누군가에게 낙찰받은 꿈을 꾸며 살고 있습니다. 다음 테이프의 주인공은 누구일까요? 꿈과 현실의 경계선 앞에서, 지금부터 경매를 시작합니다!',
      instagram: ['aeyongs2'],
      image: [
        'https://imgur.com/wULaZNE.jpg',
        'https://imgur.com/HOMPzFf.jpg',
        'https://imgur.com/Jn3QiZV.jpg',
        'https://imgur.com/wfENxoW.jpg',
        'https://imgur.com/T9uXmPZ.jpg',
      ],
      video: [],
    },
  ],
  [
    // 드로마픽
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: '수살귀',
      author: '',
      text: '물에 비친 도망자를 발견한 수살귀: 映 반사를 통해 도망자의 몸에 자신을 투영하려한다. 거울 속 도망자의 죽음을 부르는 수살귀와 끊임없이 흔들리는 도망자, 두 존재의 끔찍한 교감을 담아냈다.\r\n\r\n참여자: 남주현, 김성윤, 박소현, 안가은, 여단아, 이세라, 김건우, 정병준, 정현욱',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: '흙불땀: 젊은 예술가들에게',
      author: '',
      text: '방황하는 젊은 예술가들에게 따뜻한 조언과 위로를 전하는 도예가 이인진 작가님에 대한 다큐멘터리.\r\n\r\n참여자: 여단아, 정병준, 정현욱, 이다연',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'NOOK',
      author: '',
      text: '스위스 취리히 대학 수의학과와 홍익대학교 패션디자인과 협력 프로젝트로 디자인 된 테크웨어 패션필름 \r\n\r\n참여자: 이윤정,한준,김지호,이혜지,박기정,이다연',
      instagram: ['mmockkingjay'],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'SOBER',
      author: 'Author 2',
      text: '아이클라우드 서비스를 제공하는 가상 브랜드 프로모션 필름',
      instagram: ['mmockkingjay'],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: '한 줌의 생명이 채울 수 있는',
      author: 'Author 2',
      text: '아주 작은 존재와의 짧은 만남이 남긴 복잡 미묘한 감정을 따스하게 일렁이는 영상 속에 담아보았다.',
      instagram: ['imxmit'],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: '삼매경 samadhi 三昧境',
      author: '',
      text: '잡념을 버리고 한 가지 대상에만 정신을 집중하는 경지에 이른 사람이 있다. \r\n부디 바른 지혜를 얻고 올바르게 대상을 파악하기를.\r\n\r\n참여자: 정민경, 강동준, 이다연, 조서영',
      instagram: ['mellomaisie', 'kangdongjoonvideo', 'violetwavemovie', 'choseoyoungcho'],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'IMOOGI',
      author: '',
      text: '날아오르자. 무엇을 꿈꾸던. 용이 되어 자유로이 펼쳐보자. 비상하는 용을 꿈꾸는 이무기처럼 우리도 마음껏 꿈을 꾸고 춤을 추기를.\r\n\r\n\r\n참여자: 정병준,김민서,홍지윤,백유석',
      instagram: ['jbjoon3712'],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Crocodile(meal)',
      author: 'Author 2',
      text: '먹는 것이 재미인 악어. 코스요리로도 모자란 악어의 성찬.\r\n\r\n영상 곳곳에서 악어의 특징과 식습관을 찾아볼 수 있다.\r\n\r\n\r\n참여자: 홍지윤, 박소현, 안서원, 이다연, 이주영, 정현욱',
      instagram: ['dvonhong'],
      image: ['https://imgur.com/U4bi8PM.jpg', 'https://imgur.com/o0HIbP9.jpg', 'https://imgur.com/UvLbmi4.jpg'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: '우리가 오직 (숫자)여야만 할 수 있는 것들!',
      author: '',
      text: '(숫자)여야만 의미 있는 것들이 있다. 가령, 혼자여야만 의미있는 행동 등! 6명이 해야만 설득력이 있는 것에는 무엇이 있을까? 이때 숫자는 일상적인 것일 수도, 아이코닉한 메타포일 수도 있다. 세상에 의미 없는 숫자는 없다. 숫자는 계속된다. 인생은 계속된다!\r\n\r\n참여자: 홍지윤, 김민서, 김성윤, 김채은, 남주현, 문을주, 박소현, 안가은, 안서원, 오연재, 이다연, 이은제, 이주영, 최세은',
      instagram: ['dvonhong', 'violetmoviewave'],
      image: ['https://imgur.com/JyaXBz8.jpg', 'https://imgur.com/GwCHIai.jpg', 'https://imgur.com/gNpbLv5.jpg'],
      video: ['https://www.youtube.com/embed/E462KLVfYnQ?si=MoiZBkUX07snyoHV'],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: '무제',
      author: '',
      text: '이름 붙여지지 않은 다수한 실험을 응원하며.',
      instagram: ['now_iz'],
      image: ['https://imgur.com/0SGztO8.jpg', 'https://imgur.com/XWOemCh.jpg'],
      video: [],
    },
  ],
  [
    // 아이레이
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: '아이레이',
      author: 'Author 1',
      text: 'Description 1',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
  ],
  [
    // 야즈
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: '야즈',
      author: 'Author 1',
      text: 'Description 1',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
  ],
  [
    // 애드레날린
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
  ],
  [
    // 프로토
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
  ],
  [
    // 하이픈
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
  ],
  [
    // 한글꼴연구회
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
  ],

  [
    // 힙스
    {
      thumbnail: 'https://example.com/image1.jpg',
      title: 'Title 1',
      author: 'Author 1',
      text: 'Description 1',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
    {
      thumbnail: 'https://example.com/image2.jpg',
      title: 'Title 2',
      author: 'Author 2',
      text: 'Description 2',
      instagram: [''],
      image: ['imageurl1', 'imageurl2'],
      video: [],
    },
  ],
];
